// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer
{
    /// <summary>
    /// Agent Token resource
    /// </summary>
    [AstronomerResourceType("astronomer:index/agentToken:AgentToken")]
    public partial class AgentToken : global::Pulumi.CustomResource
    {
        /// <summary>
        /// ID of the deployment this agent token belongs to
        /// </summary>
        [Output("deploymentId")]
        public Output<string> DeploymentId { get; private set; } = null!;

        /// <summary>
        /// Agent Token description
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Agent Token expiry period in days. If not set, the token will not expire.
        /// </summary>
        [Output("expiryPeriodInDays")]
        public Output<int?> ExpiryPeriodInDays { get; private set; } = null!;

        /// <summary>
        /// Agent Token name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Agent Token value. Warning: This value will be saved in plaintext in the terraform state file.
        /// </summary>
        [Output("token")]
        public Output<string> Token { get; private set; } = null!;


        /// <summary>
        /// Create a AgentToken resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AgentToken(string name, AgentTokenArgs args, CustomResourceOptions? options = null)
            : base("astronomer:index/agentToken:AgentToken", name, args ?? new AgentTokenArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AgentToken(string name, Input<string> id, AgentTokenState? state = null, CustomResourceOptions? options = null)
            : base("astronomer:index/agentToken:AgentToken", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/ryan-pip/pulumi-astronomer",
                AdditionalSecretOutputs =
                {
                    "token",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AgentToken resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AgentToken Get(string name, Input<string> id, AgentTokenState? state = null, CustomResourceOptions? options = null)
        {
            return new AgentToken(name, id, state, options);
        }
    }

    public sealed class AgentTokenArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ID of the deployment this agent token belongs to
        /// </summary>
        [Input("deploymentId", required: true)]
        public Input<string> DeploymentId { get; set; } = null!;

        /// <summary>
        /// Agent Token description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Agent Token expiry period in days. If not set, the token will not expire.
        /// </summary>
        [Input("expiryPeriodInDays")]
        public Input<int>? ExpiryPeriodInDays { get; set; }

        /// <summary>
        /// Agent Token name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public AgentTokenArgs()
        {
        }
        public static new AgentTokenArgs Empty => new AgentTokenArgs();
    }

    public sealed class AgentTokenState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ID of the deployment this agent token belongs to
        /// </summary>
        [Input("deploymentId")]
        public Input<string>? DeploymentId { get; set; }

        /// <summary>
        /// Agent Token description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Agent Token expiry period in days. If not set, the token will not expire.
        /// </summary>
        [Input("expiryPeriodInDays")]
        public Input<int>? ExpiryPeriodInDays { get; set; }

        /// <summary>
        /// Agent Token name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("token")]
        private Input<string>? _token;

        /// <summary>
        /// Agent Token value. Warning: This value will be saved in plaintext in the terraform state file.
        /// </summary>
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public AgentTokenState()
        {
        }
        public static new AgentTokenState Empty => new AgentTokenState();
    }
}
