// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer
{
    /// <summary>
    /// Alert resource
    /// </summary>
    [AstronomerResourceType("astronomer:index/alert:Alert")]
    public partial class Alert : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Alert creation timestamp
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Alert creator
        /// </summary>
        [Output("createdBy")]
        public Output<Outputs.AlertCreatedBy> CreatedBy { get; private set; } = null!;

        /// <summary>
        /// The ID of the Deployment to which the alert is scoped
        /// </summary>
        [Output("deploymentId")]
        public Output<string> DeploymentId { get; private set; } = null!;

        /// <summary>
        /// The entity ID the alert is associated with
        /// </summary>
        [Output("entityId")]
        public Output<string> EntityId { get; private set; } = null!;

        /// <summary>
        /// The name of the entity the alert is associated with
        /// </summary>
        [Output("entityName")]
        public Output<string> EntityName { get; private set; } = null!;

        /// <summary>
        /// The ID of the Deployment to which the alert is scoped
        /// </summary>
        [Output("entityType")]
        public Output<string> EntityType { get; private set; } = null!;

        /// <summary>
        /// Alert name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Set of notification channel identifiers to notify when the alert is triggered
        /// </summary>
        [Output("notificationChannelIds")]
        public Output<ImmutableArray<string>> NotificationChannelIds { get; private set; } = null!;

        /// <summary>
        /// The notification channels to send alerts to
        /// </summary>
        [Output("notificationChannels")]
        public Output<ImmutableArray<Outputs.AlertNotificationChannel>> NotificationChannels { get; private set; } = null!;

        /// <summary>
        /// Alert rules defining the conditions for triggering the alert
        /// </summary>
        [Output("rules")]
        public Output<Outputs.AlertRules> Rules { get; private set; } = null!;

        /// <summary>
        /// The alert's severity
        /// </summary>
        [Output("severity")]
        public Output<string> Severity { get; private set; } = null!;

        /// <summary>
        /// The alert's type
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// Alert last updated timestamp
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// Alert updater
        /// </summary>
        [Output("updatedBy")]
        public Output<Outputs.AlertUpdatedBy> UpdatedBy { get; private set; } = null!;

        /// <summary>
        /// The ID of the Workspace to which the alert is scoped
        /// </summary>
        [Output("workspaceId")]
        public Output<string> WorkspaceId { get; private set; } = null!;


        /// <summary>
        /// Create a Alert resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Alert(string name, AlertArgs args, CustomResourceOptions? options = null)
            : base("astronomer:index/alert:Alert", name, args ?? new AlertArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Alert(string name, Input<string> id, AlertState? state = null, CustomResourceOptions? options = null)
            : base("astronomer:index/alert:Alert", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/ryan-pip/pulumi-astronomer",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Alert resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Alert Get(string name, Input<string> id, AlertState? state = null, CustomResourceOptions? options = null)
        {
            return new Alert(name, id, state, options);
        }
    }

    public sealed class AlertArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The entity ID the alert is associated with
        /// </summary>
        [Input("entityId", required: true)]
        public Input<string> EntityId { get; set; } = null!;

        /// <summary>
        /// The ID of the Deployment to which the alert is scoped
        /// </summary>
        [Input("entityType", required: true)]
        public Input<string> EntityType { get; set; } = null!;

        /// <summary>
        /// Alert name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("notificationChannelIds", required: true)]
        private InputList<string>? _notificationChannelIds;

        /// <summary>
        /// Set of notification channel identifiers to notify when the alert is triggered
        /// </summary>
        public InputList<string> NotificationChannelIds
        {
            get => _notificationChannelIds ?? (_notificationChannelIds = new InputList<string>());
            set => _notificationChannelIds = value;
        }

        /// <summary>
        /// Alert rules defining the conditions for triggering the alert
        /// </summary>
        [Input("rules", required: true)]
        public Input<Inputs.AlertRulesArgs> Rules { get; set; } = null!;

        /// <summary>
        /// The alert's severity
        /// </summary>
        [Input("severity", required: true)]
        public Input<string> Severity { get; set; } = null!;

        /// <summary>
        /// The alert's type
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public AlertArgs()
        {
        }
        public static new AlertArgs Empty => new AlertArgs();
    }

    public sealed class AlertState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Alert creation timestamp
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Alert creator
        /// </summary>
        [Input("createdBy")]
        public Input<Inputs.AlertCreatedByGetArgs>? CreatedBy { get; set; }

        /// <summary>
        /// The ID of the Deployment to which the alert is scoped
        /// </summary>
        [Input("deploymentId")]
        public Input<string>? DeploymentId { get; set; }

        /// <summary>
        /// The entity ID the alert is associated with
        /// </summary>
        [Input("entityId")]
        public Input<string>? EntityId { get; set; }

        /// <summary>
        /// The name of the entity the alert is associated with
        /// </summary>
        [Input("entityName")]
        public Input<string>? EntityName { get; set; }

        /// <summary>
        /// The ID of the Deployment to which the alert is scoped
        /// </summary>
        [Input("entityType")]
        public Input<string>? EntityType { get; set; }

        /// <summary>
        /// Alert name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("notificationChannelIds")]
        private InputList<string>? _notificationChannelIds;

        /// <summary>
        /// Set of notification channel identifiers to notify when the alert is triggered
        /// </summary>
        public InputList<string> NotificationChannelIds
        {
            get => _notificationChannelIds ?? (_notificationChannelIds = new InputList<string>());
            set => _notificationChannelIds = value;
        }

        [Input("notificationChannels")]
        private InputList<Inputs.AlertNotificationChannelGetArgs>? _notificationChannels;

        /// <summary>
        /// The notification channels to send alerts to
        /// </summary>
        public InputList<Inputs.AlertNotificationChannelGetArgs> NotificationChannels
        {
            get => _notificationChannels ?? (_notificationChannels = new InputList<Inputs.AlertNotificationChannelGetArgs>());
            set => _notificationChannels = value;
        }

        /// <summary>
        /// Alert rules defining the conditions for triggering the alert
        /// </summary>
        [Input("rules")]
        public Input<Inputs.AlertRulesGetArgs>? Rules { get; set; }

        /// <summary>
        /// The alert's severity
        /// </summary>
        [Input("severity")]
        public Input<string>? Severity { get; set; }

        /// <summary>
        /// The alert's type
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Alert last updated timestamp
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        /// <summary>
        /// Alert updater
        /// </summary>
        [Input("updatedBy")]
        public Input<Inputs.AlertUpdatedByGetArgs>? UpdatedBy { get; set; }

        /// <summary>
        /// The ID of the Workspace to which the alert is scoped
        /// </summary>
        [Input("workspaceId")]
        public Input<string>? WorkspaceId { get; set; }

        public AlertState()
        {
        }
        public static new AlertState Empty => new AlertState();
    }
}
