// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer
{
    public static class GetAlert
    {
        /// <summary>
        /// Alert data source
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Astronomer = RyanPip.Astronomer;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleAlert = Astronomer.Index.GetAlert.Invoke(new()
        ///     {
        ///         Id = "cm4ntm56001gk01mbhudv1elv",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["alert"] = exampleAlert,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetAlertResult> InvokeAsync(GetAlertArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAlertResult>("astronomer:index/getAlert:getAlert", args ?? new GetAlertArgs(), options.WithDefaults());

        /// <summary>
        /// Alert data source
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Astronomer = RyanPip.Astronomer;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleAlert = Astronomer.Index.GetAlert.Invoke(new()
        ///     {
        ///         Id = "cm4ntm56001gk01mbhudv1elv",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["alert"] = exampleAlert,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetAlertResult> Invoke(GetAlertInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAlertResult>("astronomer:index/getAlert:getAlert", args ?? new GetAlertInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Alert data source
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Astronomer = RyanPip.Astronomer;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleAlert = Astronomer.Index.GetAlert.Invoke(new()
        ///     {
        ///         Id = "cm4ntm56001gk01mbhudv1elv",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["alert"] = exampleAlert,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetAlertResult> Invoke(GetAlertInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAlertResult>("astronomer:index/getAlert:getAlert", args ?? new GetAlertInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAlertArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Alert identifier
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetAlertArgs()
        {
        }
        public static new GetAlertArgs Empty => new GetAlertArgs();
    }

    public sealed class GetAlertInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Alert identifier
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetAlertInvokeArgs()
        {
        }
        public static new GetAlertInvokeArgs Empty => new GetAlertInvokeArgs();
    }


    [OutputType]
    public sealed class GetAlertResult
    {
        /// <summary>
        /// Alert creation timestamp
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Alert creator
        /// </summary>
        public readonly Outputs.GetAlertCreatedByResult CreatedBy;
        /// <summary>
        /// Deployment identifier associated with the alert
        /// </summary>
        public readonly string DeploymentId;
        /// <summary>
        /// Entity identifier associated with the alert
        /// </summary>
        public readonly string EntityId;
        /// <summary>
        /// Name of the entity associated with the alert
        /// </summary>
        public readonly string EntityName;
        /// <summary>
        /// Type of entity associated with the alert (e.g., 'DEPLOYMENT')
        /// </summary>
        public readonly string EntityType;
        /// <summary>
        /// Alert identifier
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Alert name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The notification channels to send alerts to
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAlertNotificationChannelResult> NotificationChannels;
        /// <summary>
        /// Alert rules defining the conditions for triggering the alert
        /// </summary>
        public readonly Outputs.GetAlertRulesResult Rules;
        /// <summary>
        /// Severity level of the alert (e.g., 'INFO', 'WARNING', 'CRITICAL')
        /// </summary>
        public readonly string Severity;
        /// <summary>
        /// Type of alert (e.g., 'DAG*SUCCESS', 'DAG*FAILURE')
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Alert last updated timestamp
        /// </summary>
        public readonly string UpdatedAt;
        /// <summary>
        /// Alert updater
        /// </summary>
        public readonly Outputs.GetAlertUpdatedByResult UpdatedBy;
        /// <summary>
        /// Workspace identifier associated with the alert
        /// </summary>
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetAlertResult(
            string createdAt,

            Outputs.GetAlertCreatedByResult createdBy,

            string deploymentId,

            string entityId,

            string entityName,

            string entityType,

            string id,

            string name,

            ImmutableArray<Outputs.GetAlertNotificationChannelResult> notificationChannels,

            Outputs.GetAlertRulesResult rules,

            string severity,

            string type,

            string updatedAt,

            Outputs.GetAlertUpdatedByResult updatedBy,

            string workspaceId)
        {
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            DeploymentId = deploymentId;
            EntityId = entityId;
            EntityName = entityName;
            EntityType = entityType;
            Id = id;
            Name = name;
            NotificationChannels = notificationChannels;
            Rules = rules;
            Severity = severity;
            Type = type;
            UpdatedAt = updatedAt;
            UpdatedBy = updatedBy;
            WorkspaceId = workspaceId;
        }
    }
}
