// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer
{
    public static class GetNotificationChannels
    {
        /// <summary>
        /// Notification Channels data source
        /// 
        /// ## Example Usage
        /// </summary>
        public static Task<GetNotificationChannelsResult> InvokeAsync(GetNotificationChannelsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetNotificationChannelsResult>("astronomer:index/getNotificationChannels:getNotificationChannels", args ?? new GetNotificationChannelsArgs(), options.WithDefaults());

        /// <summary>
        /// Notification Channels data source
        /// 
        /// ## Example Usage
        /// </summary>
        public static Output<GetNotificationChannelsResult> Invoke(GetNotificationChannelsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetNotificationChannelsResult>("astronomer:index/getNotificationChannels:getNotificationChannels", args ?? new GetNotificationChannelsInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Notification Channels data source
        /// 
        /// ## Example Usage
        /// </summary>
        public static Output<GetNotificationChannelsResult> Invoke(GetNotificationChannelsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetNotificationChannelsResult>("astronomer:index/getNotificationChannels:getNotificationChannels", args ?? new GetNotificationChannelsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNotificationChannelsArgs : global::Pulumi.InvokeArgs
    {
        [Input("channelTypes")]
        private List<string>? _channelTypes;
        public List<string> ChannelTypes
        {
            get => _channelTypes ?? (_channelTypes = new List<string>());
            set => _channelTypes = value;
        }

        [Input("deploymentIds")]
        private List<string>? _deploymentIds;
        public List<string> DeploymentIds
        {
            get => _deploymentIds ?? (_deploymentIds = new List<string>());
            set => _deploymentIds = value;
        }

        [Input("entityType")]
        public string? EntityType { get; set; }

        [Input("notificationChannelIds")]
        private List<string>? _notificationChannelIds;
        public List<string> NotificationChannelIds
        {
            get => _notificationChannelIds ?? (_notificationChannelIds = new List<string>());
            set => _notificationChannelIds = value;
        }

        [Input("workspaceIds")]
        private List<string>? _workspaceIds;
        public List<string> WorkspaceIds
        {
            get => _workspaceIds ?? (_workspaceIds = new List<string>());
            set => _workspaceIds = value;
        }

        public GetNotificationChannelsArgs()
        {
        }
        public static new GetNotificationChannelsArgs Empty => new GetNotificationChannelsArgs();
    }

    public sealed class GetNotificationChannelsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("channelTypes")]
        private InputList<string>? _channelTypes;
        public InputList<string> ChannelTypes
        {
            get => _channelTypes ?? (_channelTypes = new InputList<string>());
            set => _channelTypes = value;
        }

        [Input("deploymentIds")]
        private InputList<string>? _deploymentIds;
        public InputList<string> DeploymentIds
        {
            get => _deploymentIds ?? (_deploymentIds = new InputList<string>());
            set => _deploymentIds = value;
        }

        [Input("entityType")]
        public Input<string>? EntityType { get; set; }

        [Input("notificationChannelIds")]
        private InputList<string>? _notificationChannelIds;
        public InputList<string> NotificationChannelIds
        {
            get => _notificationChannelIds ?? (_notificationChannelIds = new InputList<string>());
            set => _notificationChannelIds = value;
        }

        [Input("workspaceIds")]
        private InputList<string>? _workspaceIds;
        public InputList<string> WorkspaceIds
        {
            get => _workspaceIds ?? (_workspaceIds = new InputList<string>());
            set => _workspaceIds = value;
        }

        public GetNotificationChannelsInvokeArgs()
        {
        }
        public static new GetNotificationChannelsInvokeArgs Empty => new GetNotificationChannelsInvokeArgs();
    }


    [OutputType]
    public sealed class GetNotificationChannelsResult
    {
        public readonly ImmutableArray<string> ChannelTypes;
        public readonly ImmutableArray<string> DeploymentIds;
        public readonly string? EntityType;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> NotificationChannelIds;
        public readonly ImmutableArray<Outputs.GetNotificationChannelsNotificationChannelResult> NotificationChannels;
        public readonly ImmutableArray<string> WorkspaceIds;

        [OutputConstructor]
        private GetNotificationChannelsResult(
            ImmutableArray<string> channelTypes,

            ImmutableArray<string> deploymentIds,

            string? entityType,

            string id,

            ImmutableArray<string> notificationChannelIds,

            ImmutableArray<Outputs.GetNotificationChannelsNotificationChannelResult> notificationChannels,

            ImmutableArray<string> workspaceIds)
        {
            ChannelTypes = channelTypes;
            DeploymentIds = deploymentIds;
            EntityType = entityType;
            Id = id;
            NotificationChannelIds = notificationChannelIds;
            NotificationChannels = notificationChannels;
            WorkspaceIds = workspaceIds;
        }
    }
}
