// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer
{
    public static class GetNotificationChannel
    {
        /// <summary>
        /// Notification Channel data source
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Astronomer = RyanPip.Astronomer;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleNotificationChannel = Astronomer.Index.GetNotificationChannel.Invoke(new()
        ///     {
        ///         Id = "cm4nwrvyg024h01mk2dn58m5s",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["notificationChannel"] = exampleNotificationChannel,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetNotificationChannelResult> InvokeAsync(GetNotificationChannelArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetNotificationChannelResult>("astronomer:index/getNotificationChannel:getNotificationChannel", args ?? new GetNotificationChannelArgs(), options.WithDefaults());

        /// <summary>
        /// Notification Channel data source
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Astronomer = RyanPip.Astronomer;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleNotificationChannel = Astronomer.Index.GetNotificationChannel.Invoke(new()
        ///     {
        ///         Id = "cm4nwrvyg024h01mk2dn58m5s",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["notificationChannel"] = exampleNotificationChannel,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetNotificationChannelResult> Invoke(GetNotificationChannelInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetNotificationChannelResult>("astronomer:index/getNotificationChannel:getNotificationChannel", args ?? new GetNotificationChannelInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Notification Channel data source
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Astronomer = RyanPip.Astronomer;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var exampleNotificationChannel = Astronomer.Index.GetNotificationChannel.Invoke(new()
        ///     {
        ///         Id = "cm4nwrvyg024h01mk2dn58m5s",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["notificationChannel"] = exampleNotificationChannel,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetNotificationChannelResult> Invoke(GetNotificationChannelInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetNotificationChannelResult>("astronomer:index/getNotificationChannel:getNotificationChannel", args ?? new GetNotificationChannelInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNotificationChannelArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The notification channel's ID
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetNotificationChannelArgs()
        {
        }
        public static new GetNotificationChannelArgs Empty => new GetNotificationChannelArgs();
    }

    public sealed class GetNotificationChannelInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The notification channel's ID
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetNotificationChannelInvokeArgs()
        {
        }
        public static new GetNotificationChannelInvokeArgs Empty => new GetNotificationChannelInvokeArgs();
    }


    [OutputType]
    public sealed class GetNotificationChannelResult
    {
        /// <summary>
        /// Notification Channel creation timestamp
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Notification Channel creator
        /// </summary>
        public readonly Outputs.GetNotificationChannelCreatedByResult CreatedBy;
        /// <summary>
        /// The notification channel's definition
        /// </summary>
        public readonly Outputs.GetNotificationChannelDefinitionResult Definition;
        /// <summary>
        /// The deployment ID the notification channel is scoped to
        /// </summary>
        public readonly string DeploymentId;
        /// <summary>
        /// The entity ID the notification channel is scoped to
        /// </summary>
        public readonly string EntityId;
        /// <summary>
        /// The name of the entity the notification channel is scoped to
        /// </summary>
        public readonly string EntityName;
        /// <summary>
        /// The type of entity the notification channel is scoped to (e.g., 'DEPLOYMENT')
        /// </summary>
        public readonly string EntityType;
        /// <summary>
        /// The notification channel's ID
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// When entity type is scoped to ORGANIZATION or WORKSPACE, this determines if child entities can access this notification channel.
        /// </summary>
        public readonly bool IsShared;
        /// <summary>
        /// The notification channel's name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The notification channel's type
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Notification Channel last updated timestamp
        /// </summary>
        public readonly string UpdatedAt;
        /// <summary>
        /// Notification Channel updater
        /// </summary>
        public readonly Outputs.GetNotificationChannelUpdatedByResult UpdatedBy;
        /// <summary>
        /// The workspace ID the notification channel is scoped to
        /// </summary>
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetNotificationChannelResult(
            string createdAt,

            Outputs.GetNotificationChannelCreatedByResult createdBy,

            Outputs.GetNotificationChannelDefinitionResult definition,

            string deploymentId,

            string entityId,

            string entityName,

            string entityType,

            string id,

            bool isShared,

            string name,

            string type,

            string updatedAt,

            Outputs.GetNotificationChannelUpdatedByResult updatedBy,

            string workspaceId)
        {
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            Definition = definition;
            DeploymentId = deploymentId;
            EntityId = entityId;
            EntityName = entityName;
            EntityType = entityType;
            Id = id;
            IsShared = isShared;
            Name = name;
            Type = type;
            UpdatedAt = updatedAt;
            UpdatedBy = updatedBy;
            WorkspaceId = workspaceId;
        }
    }
}
