// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer
{
    /// <summary>
    /// User Invite resource
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Astronomer = RyanPip.Astronomer;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var userInvite = new Astronomer.Index.UserInvite("user_invite", new()
    ///     {
    ///         Email = "email@organization.com",
    ///         Role = "ORGANIZATION_MEMBER",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [AstronomerResourceType("astronomer:index/userInvite:UserInvite")]
    public partial class UserInvite : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The email address of the user being invited
        /// </summary>
        [Output("email")]
        public Output<string> Email { get; private set; } = null!;

        /// <summary>
        /// The expiration date of the invite
        /// </summary>
        [Output("expiresAt")]
        public Output<string> ExpiresAt { get; private set; } = null!;

        /// <summary>
        /// The ID of the invite
        /// </summary>
        [Output("inviteId")]
        public Output<string> InviteId { get; private set; } = null!;

        /// <summary>
        /// The profile of the invitee
        /// </summary>
        [Output("invitee")]
        public Output<Outputs.UserInviteInvitee> Invitee { get; private set; } = null!;

        /// <summary>
        /// The profile of the inviter
        /// </summary>
        [Output("inviter")]
        public Output<Outputs.UserInviteInviter> Inviter { get; private set; } = null!;

        /// <summary>
        /// The Organization role to assign to the user
        /// </summary>
        [Output("role")]
        public Output<string> Role { get; private set; } = null!;

        /// <summary>
        /// The ID of the user
        /// </summary>
        [Output("userId")]
        public Output<string> UserId { get; private set; } = null!;


        /// <summary>
        /// Create a UserInvite resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public UserInvite(string name, UserInviteArgs args, CustomResourceOptions? options = null)
            : base("astronomer:index/userInvite:UserInvite", name, args ?? new UserInviteArgs(), MakeResourceOptions(options, ""))
        {
        }

        private UserInvite(string name, Input<string> id, UserInviteState? state = null, CustomResourceOptions? options = null)
            : base("astronomer:index/userInvite:UserInvite", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/ryan-pip/pulumi-astronomer",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing UserInvite resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static UserInvite Get(string name, Input<string> id, UserInviteState? state = null, CustomResourceOptions? options = null)
        {
            return new UserInvite(name, id, state, options);
        }
    }

    public sealed class UserInviteArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The email address of the user being invited
        /// </summary>
        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        /// <summary>
        /// The Organization role to assign to the user
        /// </summary>
        [Input("role", required: true)]
        public Input<string> Role { get; set; } = null!;

        public UserInviteArgs()
        {
        }
        public static new UserInviteArgs Empty => new UserInviteArgs();
    }

    public sealed class UserInviteState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The email address of the user being invited
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        /// <summary>
        /// The expiration date of the invite
        /// </summary>
        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        /// <summary>
        /// The ID of the invite
        /// </summary>
        [Input("inviteId")]
        public Input<string>? InviteId { get; set; }

        /// <summary>
        /// The profile of the invitee
        /// </summary>
        [Input("invitee")]
        public Input<Inputs.UserInviteInviteeGetArgs>? Invitee { get; set; }

        /// <summary>
        /// The profile of the inviter
        /// </summary>
        [Input("inviter")]
        public Input<Inputs.UserInviteInviterGetArgs>? Inviter { get; set; }

        /// <summary>
        /// The Organization role to assign to the user
        /// </summary>
        [Input("role")]
        public Input<string>? Role { get; set; }

        /// <summary>
        /// The ID of the user
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public UserInviteState()
        {
        }
        public static new UserInviteState Empty => new UserInviteState();
    }
}
