# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['AgentTokenArgs', 'AgentToken']

@pulumi.input_type
class AgentTokenArgs:
    def __init__(__self__, *,
                 deployment_id: pulumi.Input[_builtins.str],
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 expiry_period_in_days: pulumi.Input[Optional[_builtins.int]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a AgentToken resource.

        :param pulumi.Input[_builtins.str] deployment_id: ID of the deployment this agent token belongs to
        :param pulumi.Input[_builtins.str] description: Agent Token description
        :param pulumi.Input[_builtins.int] expiry_period_in_days: Agent Token expiry period in days. If not set, the token will not expire.
        :param pulumi.Input[_builtins.str] name: Agent Token name
        """
        pulumi.set(__self__, "deployment_id", deployment_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if expiry_period_in_days is not None:
            pulumi.set(__self__, "expiry_period_in_days", expiry_period_in_days)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="deploymentId")
    def deployment_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID of the deployment this agent token belongs to
        """
        return pulumi.get(self, "deployment_id")

    @deployment_id.setter
    def deployment_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "deployment_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Agent Token description
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="expiryPeriodInDays")
    def expiry_period_in_days(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Agent Token expiry period in days. If not set, the token will not expire.
        """
        return pulumi.get(self, "expiry_period_in_days")

    @expiry_period_in_days.setter
    def expiry_period_in_days(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "expiry_period_in_days", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Agent Token name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _AgentTokenState:
    def __init__(__self__, *,
                 deployment_id: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 expiry_period_in_days: pulumi.Input[Optional[_builtins.int]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 token: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering AgentToken resources.

        :param pulumi.Input[_builtins.str] deployment_id: ID of the deployment this agent token belongs to
        :param pulumi.Input[_builtins.str] description: Agent Token description
        :param pulumi.Input[_builtins.int] expiry_period_in_days: Agent Token expiry period in days. If not set, the token will not expire.
        :param pulumi.Input[_builtins.str] name: Agent Token name
        :param pulumi.Input[_builtins.str] token: Agent Token value. Warning: This value will be saved in plaintext in the terraform state file.
        """
        if deployment_id is not None:
            pulumi.set(__self__, "deployment_id", deployment_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if expiry_period_in_days is not None:
            pulumi.set(__self__, "expiry_period_in_days", expiry_period_in_days)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter(name="deploymentId")
    def deployment_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of the deployment this agent token belongs to
        """
        return pulumi.get(self, "deployment_id")

    @deployment_id.setter
    def deployment_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "deployment_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Agent Token description
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="expiryPeriodInDays")
    def expiry_period_in_days(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Agent Token expiry period in days. If not set, the token will not expire.
        """
        return pulumi.get(self, "expiry_period_in_days")

    @expiry_period_in_days.setter
    def expiry_period_in_days(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "expiry_period_in_days", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Agent Token name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Agent Token value. Warning: This value will be saved in plaintext in the terraform state file.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "token", value)


@pulumi.type_token("astronomer:index/agentToken:AgentToken")
class AgentToken(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 deployment_id: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 expiry_period_in_days: pulumi.Input[Optional[_builtins.int]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Agent Token resource


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] deployment_id: ID of the deployment this agent token belongs to
        :param pulumi.Input[_builtins.str] description: Agent Token description
        :param pulumi.Input[_builtins.int] expiry_period_in_days: Agent Token expiry period in days. If not set, the token will not expire.
        :param pulumi.Input[_builtins.str] name: Agent Token name
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AgentTokenArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Agent Token resource


        :param str resource_name: The name of the resource.
        :param AgentTokenArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AgentTokenArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 deployment_id: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 expiry_period_in_days: pulumi.Input[Optional[_builtins.int]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AgentTokenArgs.__new__(AgentTokenArgs)

            if deployment_id is None and not opts.urn:
                raise TypeError("Missing required property 'deployment_id'")
            __props__.__dict__["deployment_id"] = deployment_id
            __props__.__dict__["description"] = description
            __props__.__dict__["expiry_period_in_days"] = expiry_period_in_days
            __props__.__dict__["name"] = name
            __props__.__dict__["token"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["token"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(AgentToken, __self__).__init__(
            'astronomer:index/agentToken:AgentToken',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            deployment_id: pulumi.Input[Optional[_builtins.str]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            expiry_period_in_days: pulumi.Input[Optional[_builtins.int]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            token: pulumi.Input[Optional[_builtins.str]] = None) -> 'AgentToken':
        """
        Get an existing AgentToken resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] deployment_id: ID of the deployment this agent token belongs to
        :param pulumi.Input[_builtins.str] description: Agent Token description
        :param pulumi.Input[_builtins.int] expiry_period_in_days: Agent Token expiry period in days. If not set, the token will not expire.
        :param pulumi.Input[_builtins.str] name: Agent Token name
        :param pulumi.Input[_builtins.str] token: Agent Token value. Warning: This value will be saved in plaintext in the terraform state file.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AgentTokenState.__new__(_AgentTokenState)

        __props__.__dict__["deployment_id"] = deployment_id
        __props__.__dict__["description"] = description
        __props__.__dict__["expiry_period_in_days"] = expiry_period_in_days
        __props__.__dict__["name"] = name
        __props__.__dict__["token"] = token
        return AgentToken(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="deploymentId")
    def deployment_id(self) -> pulumi.Output[_builtins.str]:
        """
        ID of the deployment this agent token belongs to
        """
        return pulumi.get(self, "deployment_id")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Agent Token description
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="expiryPeriodInDays")
    def expiry_period_in_days(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Agent Token expiry period in days. If not set, the token will not expire.
        """
        return pulumi.get(self, "expiry_period_in_days")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Agent Token name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Output[_builtins.str]:
        """
        Agent Token value. Warning: This value will be saved in plaintext in the terraform state file.
        """
        return pulumi.get(self, "token")

