# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetNotificationChannelsResult',
    'AwaitableGetNotificationChannelsResult',
    'get_notification_channels',
    'get_notification_channels_output',
]

@pulumi.output_type
class GetNotificationChannelsResult:
    """
    A collection of values returned by getNotificationChannels.
    """
    def __init__(__self__, channel_types=None, deployment_ids=None, entity_type=None, id=None, notification_channel_ids=None, notification_channels=None, workspace_ids=None):
        if channel_types and not isinstance(channel_types, list):
            raise TypeError("Expected argument 'channel_types' to be a list")
        pulumi.set(__self__, "channel_types", channel_types)
        if deployment_ids and not isinstance(deployment_ids, list):
            raise TypeError("Expected argument 'deployment_ids' to be a list")
        pulumi.set(__self__, "deployment_ids", deployment_ids)
        if entity_type and not isinstance(entity_type, str):
            raise TypeError("Expected argument 'entity_type' to be a str")
        pulumi.set(__self__, "entity_type", entity_type)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if notification_channel_ids and not isinstance(notification_channel_ids, list):
            raise TypeError("Expected argument 'notification_channel_ids' to be a list")
        pulumi.set(__self__, "notification_channel_ids", notification_channel_ids)
        if notification_channels and not isinstance(notification_channels, list):
            raise TypeError("Expected argument 'notification_channels' to be a list")
        pulumi.set(__self__, "notification_channels", notification_channels)
        if workspace_ids and not isinstance(workspace_ids, list):
            raise TypeError("Expected argument 'workspace_ids' to be a list")
        pulumi.set(__self__, "workspace_ids", workspace_ids)

    @_builtins.property
    @pulumi.getter(name="channelTypes")
    def channel_types(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "channel_types")

    @_builtins.property
    @pulumi.getter(name="deploymentIds")
    def deployment_ids(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "deployment_ids")

    @_builtins.property
    @pulumi.getter(name="entityType")
    def entity_type(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "entity_type")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="notificationChannelIds")
    def notification_channel_ids(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "notification_channel_ids")

    @_builtins.property
    @pulumi.getter(name="notificationChannels")
    def notification_channels(self) -> Sequence['outputs.GetNotificationChannelsNotificationChannelResult']:
        return pulumi.get(self, "notification_channels")

    @_builtins.property
    @pulumi.getter(name="workspaceIds")
    def workspace_ids(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "workspace_ids")


class AwaitableGetNotificationChannelsResult(GetNotificationChannelsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetNotificationChannelsResult(
            channel_types=self.channel_types,
            deployment_ids=self.deployment_ids,
            entity_type=self.entity_type,
            id=self.id,
            notification_channel_ids=self.notification_channel_ids,
            notification_channels=self.notification_channels,
            workspace_ids=self.workspace_ids)


def get_notification_channels(channel_types: Optional[Sequence[_builtins.str]] = None,
                              deployment_ids: Optional[Sequence[_builtins.str]] = None,
                              entity_type: Optional[_builtins.str] = None,
                              notification_channel_ids: Optional[Sequence[_builtins.str]] = None,
                              workspace_ids: Optional[Sequence[_builtins.str]] = None,
                              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetNotificationChannelsResult:
    """
    Notification Channels data source

    ## Example Usage
    """
    __args__ = dict()
    __args__['channelTypes'] = channel_types
    __args__['deploymentIds'] = deployment_ids
    __args__['entityType'] = entity_type
    __args__['notificationChannelIds'] = notification_channel_ids
    __args__['workspaceIds'] = workspace_ids
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('astronomer:index/getNotificationChannels:getNotificationChannels', __args__, opts=opts, typ=GetNotificationChannelsResult).value

    return AwaitableGetNotificationChannelsResult(
        channel_types=pulumi.get(__ret__, 'channel_types'),
        deployment_ids=pulumi.get(__ret__, 'deployment_ids'),
        entity_type=pulumi.get(__ret__, 'entity_type'),
        id=pulumi.get(__ret__, 'id'),
        notification_channel_ids=pulumi.get(__ret__, 'notification_channel_ids'),
        notification_channels=pulumi.get(__ret__, 'notification_channels'),
        workspace_ids=pulumi.get(__ret__, 'workspace_ids'))
def get_notification_channels_output(channel_types: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                                     deployment_ids: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                                     entity_type: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                     notification_channel_ids: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                                     workspace_ids: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetNotificationChannelsResult]:
    """
    Notification Channels data source

    ## Example Usage
    """
    __args__ = dict()
    __args__['channelTypes'] = channel_types
    __args__['deploymentIds'] = deployment_ids
    __args__['entityType'] = entity_type
    __args__['notificationChannelIds'] = notification_channel_ids
    __args__['workspaceIds'] = workspace_ids
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('astronomer:index/getNotificationChannels:getNotificationChannels', __args__, opts=opts, typ=GetNotificationChannelsResult)
    return __ret__.apply(lambda __response__: GetNotificationChannelsResult(
        channel_types=pulumi.get(__response__, 'channel_types'),
        deployment_ids=pulumi.get(__response__, 'deployment_ids'),
        entity_type=pulumi.get(__response__, 'entity_type'),
        id=pulumi.get(__response__, 'id'),
        notification_channel_ids=pulumi.get(__response__, 'notification_channel_ids'),
        notification_channels=pulumi.get(__response__, 'notification_channels'),
        workspace_ids=pulumi.get(__response__, 'workspace_ids')))
