// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package astronomer

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/ryan-pip/pulumi-astronomer/sdk/go/astronomer/internal"
)

// Custom role resource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/ryan-pip/pulumi-astronomer/sdk/go/astronomer"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := astronomer.NewCustomRole(ctx, "example", &astronomer.CustomRoleArgs{
//				Name:        pulumi.String("Deployment_Viewer"),
//				Description: pulumi.String("Custom role for viewing deployments"),
//				ScopeType:   pulumi.String("DEPLOYMENT"),
//				Permissions: pulumi.StringArray{
//					pulumi.String("deployment.get"),
//					pulumi.String("deployment.delete"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Custom role with restricted workspace access
//			_, err = astronomer.NewCustomRole(ctx, "restricted_example", &astronomer.CustomRoleArgs{
//				Name:        pulumi.String("Limited_Deployment_Viewer"),
//				Description: pulumi.String("Custom role restricted to specific workspaces"),
//				ScopeType:   pulumi.String("DEPLOYMENT"),
//				Permissions: pulumi.StringArray{
//					pulumi.String("deployment.get"),
//				},
//				RestrictedWorkspaceIds: pulumi.StringArray{
//					pulumi.String("clxxxxxxxxxxxx"),
//					pulumi.String("clyyyyyyyyyyyyy"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type CustomRole struct {
	pulumi.CustomResourceState

	// The time the custom role was created
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The subject who created the custom role
	CreatedBy CustomRoleCreatedByOutput `pulumi:"createdBy"`
	// The custom role's description
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The custom role's name
	Name pulumi.StringOutput `pulumi:"name"`
	// The custom role's permissions
	Permissions pulumi.StringArrayOutput `pulumi:"permissions"`
	// The IDs of Workspaces that the custom role is restricted to
	RestrictedWorkspaceIds pulumi.StringArrayOutput `pulumi:"restrictedWorkspaceIds"`
	// The custom role's scope (DEPLOYMENT or DAG)
	ScopeType pulumi.StringOutput `pulumi:"scopeType"`
	// The time the custom role was last updated
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// The subject who last updated the custom role
	UpdatedBy CustomRoleUpdatedByOutput `pulumi:"updatedBy"`
}

// NewCustomRole registers a new resource with the given unique name, arguments, and options.
func NewCustomRole(ctx *pulumi.Context,
	name string, args *CustomRoleArgs, opts ...pulumi.ResourceOption) (*CustomRole, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Permissions == nil {
		return nil, errors.New("invalid value for required argument 'Permissions'")
	}
	if args.ScopeType == nil {
		return nil, errors.New("invalid value for required argument 'ScopeType'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CustomRole
	err := ctx.RegisterResource("astronomer:index/customRole:CustomRole", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCustomRole gets an existing CustomRole resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCustomRole(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CustomRoleState, opts ...pulumi.ResourceOption) (*CustomRole, error) {
	var resource CustomRole
	err := ctx.ReadResource("astronomer:index/customRole:CustomRole", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CustomRole resources.
type customRoleState struct {
	// The time the custom role was created
	CreatedAt *string `pulumi:"createdAt"`
	// The subject who created the custom role
	CreatedBy *CustomRoleCreatedBy `pulumi:"createdBy"`
	// The custom role's description
	Description *string `pulumi:"description"`
	// The custom role's name
	Name *string `pulumi:"name"`
	// The custom role's permissions
	Permissions []string `pulumi:"permissions"`
	// The IDs of Workspaces that the custom role is restricted to
	RestrictedWorkspaceIds []string `pulumi:"restrictedWorkspaceIds"`
	// The custom role's scope (DEPLOYMENT or DAG)
	ScopeType *string `pulumi:"scopeType"`
	// The time the custom role was last updated
	UpdatedAt *string `pulumi:"updatedAt"`
	// The subject who last updated the custom role
	UpdatedBy *CustomRoleUpdatedBy `pulumi:"updatedBy"`
}

type CustomRoleState struct {
	// The time the custom role was created
	CreatedAt pulumi.StringPtrInput
	// The subject who created the custom role
	CreatedBy CustomRoleCreatedByPtrInput
	// The custom role's description
	Description pulumi.StringPtrInput
	// The custom role's name
	Name pulumi.StringPtrInput
	// The custom role's permissions
	Permissions pulumi.StringArrayInput
	// The IDs of Workspaces that the custom role is restricted to
	RestrictedWorkspaceIds pulumi.StringArrayInput
	// The custom role's scope (DEPLOYMENT or DAG)
	ScopeType pulumi.StringPtrInput
	// The time the custom role was last updated
	UpdatedAt pulumi.StringPtrInput
	// The subject who last updated the custom role
	UpdatedBy CustomRoleUpdatedByPtrInput
}

func (CustomRoleState) ElementType() reflect.Type {
	return reflect.TypeOf((*customRoleState)(nil)).Elem()
}

type customRoleArgs struct {
	// The custom role's description
	Description *string `pulumi:"description"`
	// The custom role's name
	Name *string `pulumi:"name"`
	// The custom role's permissions
	Permissions []string `pulumi:"permissions"`
	// The IDs of Workspaces that the custom role is restricted to
	RestrictedWorkspaceIds []string `pulumi:"restrictedWorkspaceIds"`
	// The custom role's scope (DEPLOYMENT or DAG)
	ScopeType string `pulumi:"scopeType"`
}

// The set of arguments for constructing a CustomRole resource.
type CustomRoleArgs struct {
	// The custom role's description
	Description pulumi.StringPtrInput
	// The custom role's name
	Name pulumi.StringPtrInput
	// The custom role's permissions
	Permissions pulumi.StringArrayInput
	// The IDs of Workspaces that the custom role is restricted to
	RestrictedWorkspaceIds pulumi.StringArrayInput
	// The custom role's scope (DEPLOYMENT or DAG)
	ScopeType pulumi.StringInput
}

func (CustomRoleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*customRoleArgs)(nil)).Elem()
}

type CustomRoleInput interface {
	pulumi.Input

	ToCustomRoleOutput() CustomRoleOutput
	ToCustomRoleOutputWithContext(ctx context.Context) CustomRoleOutput
}

func (*CustomRole) ElementType() reflect.Type {
	return reflect.TypeOf((**CustomRole)(nil)).Elem()
}

func (i *CustomRole) ToCustomRoleOutput() CustomRoleOutput {
	return i.ToCustomRoleOutputWithContext(context.Background())
}

func (i *CustomRole) ToCustomRoleOutputWithContext(ctx context.Context) CustomRoleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomRoleOutput)
}

// CustomRoleArrayInput is an input type that accepts CustomRoleArray and CustomRoleArrayOutput values.
// You can construct a concrete instance of `CustomRoleArrayInput` via:
//
//	CustomRoleArray{ CustomRoleArgs{...} }
type CustomRoleArrayInput interface {
	pulumi.Input

	ToCustomRoleArrayOutput() CustomRoleArrayOutput
	ToCustomRoleArrayOutputWithContext(context.Context) CustomRoleArrayOutput
}

type CustomRoleArray []CustomRoleInput

func (CustomRoleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CustomRole)(nil)).Elem()
}

func (i CustomRoleArray) ToCustomRoleArrayOutput() CustomRoleArrayOutput {
	return i.ToCustomRoleArrayOutputWithContext(context.Background())
}

func (i CustomRoleArray) ToCustomRoleArrayOutputWithContext(ctx context.Context) CustomRoleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomRoleArrayOutput)
}

// CustomRoleMapInput is an input type that accepts CustomRoleMap and CustomRoleMapOutput values.
// You can construct a concrete instance of `CustomRoleMapInput` via:
//
//	CustomRoleMap{ "key": CustomRoleArgs{...} }
type CustomRoleMapInput interface {
	pulumi.Input

	ToCustomRoleMapOutput() CustomRoleMapOutput
	ToCustomRoleMapOutputWithContext(context.Context) CustomRoleMapOutput
}

type CustomRoleMap map[string]CustomRoleInput

func (CustomRoleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CustomRole)(nil)).Elem()
}

func (i CustomRoleMap) ToCustomRoleMapOutput() CustomRoleMapOutput {
	return i.ToCustomRoleMapOutputWithContext(context.Background())
}

func (i CustomRoleMap) ToCustomRoleMapOutputWithContext(ctx context.Context) CustomRoleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomRoleMapOutput)
}

type CustomRoleOutput struct{ *pulumi.OutputState }

func (CustomRoleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CustomRole)(nil)).Elem()
}

func (o CustomRoleOutput) ToCustomRoleOutput() CustomRoleOutput {
	return o
}

func (o CustomRoleOutput) ToCustomRoleOutputWithContext(ctx context.Context) CustomRoleOutput {
	return o
}

// The time the custom role was created
func (o CustomRoleOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomRole) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The subject who created the custom role
func (o CustomRoleOutput) CreatedBy() CustomRoleCreatedByOutput {
	return o.ApplyT(func(v *CustomRole) CustomRoleCreatedByOutput { return v.CreatedBy }).(CustomRoleCreatedByOutput)
}

// The custom role's description
func (o CustomRoleOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CustomRole) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The custom role's name
func (o CustomRoleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomRole) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The custom role's permissions
func (o CustomRoleOutput) Permissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *CustomRole) pulumi.StringArrayOutput { return v.Permissions }).(pulumi.StringArrayOutput)
}

// The IDs of Workspaces that the custom role is restricted to
func (o CustomRoleOutput) RestrictedWorkspaceIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *CustomRole) pulumi.StringArrayOutput { return v.RestrictedWorkspaceIds }).(pulumi.StringArrayOutput)
}

// The custom role's scope (DEPLOYMENT or DAG)
func (o CustomRoleOutput) ScopeType() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomRole) pulumi.StringOutput { return v.ScopeType }).(pulumi.StringOutput)
}

// The time the custom role was last updated
func (o CustomRoleOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomRole) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// The subject who last updated the custom role
func (o CustomRoleOutput) UpdatedBy() CustomRoleUpdatedByOutput {
	return o.ApplyT(func(v *CustomRole) CustomRoleUpdatedByOutput { return v.UpdatedBy }).(CustomRoleUpdatedByOutput)
}

type CustomRoleArrayOutput struct{ *pulumi.OutputState }

func (CustomRoleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CustomRole)(nil)).Elem()
}

func (o CustomRoleArrayOutput) ToCustomRoleArrayOutput() CustomRoleArrayOutput {
	return o
}

func (o CustomRoleArrayOutput) ToCustomRoleArrayOutputWithContext(ctx context.Context) CustomRoleArrayOutput {
	return o
}

func (o CustomRoleArrayOutput) Index(i pulumi.IntInput) CustomRoleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CustomRole {
		return vs[0].([]*CustomRole)[vs[1].(int)]
	}).(CustomRoleOutput)
}

type CustomRoleMapOutput struct{ *pulumi.OutputState }

func (CustomRoleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CustomRole)(nil)).Elem()
}

func (o CustomRoleMapOutput) ToCustomRoleMapOutput() CustomRoleMapOutput {
	return o
}

func (o CustomRoleMapOutput) ToCustomRoleMapOutputWithContext(ctx context.Context) CustomRoleMapOutput {
	return o
}

func (o CustomRoleMapOutput) MapIndex(k pulumi.StringInput) CustomRoleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CustomRole {
		return vs[0].(map[string]*CustomRole)[vs[1].(string)]
	}).(CustomRoleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CustomRoleInput)(nil)).Elem(), &CustomRole{})
	pulumi.RegisterInputType(reflect.TypeOf((*CustomRoleArrayInput)(nil)).Elem(), CustomRoleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CustomRoleMapInput)(nil)).Elem(), CustomRoleMap{})
	pulumi.RegisterOutputType(CustomRoleOutput{})
	pulumi.RegisterOutputType(CustomRoleArrayOutput{})
	pulumi.RegisterOutputType(CustomRoleMapOutput{})
}
