// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package astronomer

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/ryan-pip/pulumi-astronomer/sdk/go/astronomer/internal"
)

// Environment Object data source
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/ryan-pip/pulumi-astronomer/sdk/go/astronomer"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			exampleEnvironmentObject, err := astronomer.GetEnvironmentObject(ctx, &astronomer.LookupEnvironmentObjectArgs{
//				Id: "cm4ntm56001gk01mbhudv1elv",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("environmentObject", exampleEnvironmentObject)
//			return nil
//		})
//	}
//
// ```
func LookupEnvironmentObject(ctx *pulumi.Context, args *LookupEnvironmentObjectArgs, opts ...pulumi.InvokeOption) (*LookupEnvironmentObjectResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupEnvironmentObjectResult
	err := ctx.Invoke("astronomer:index/getEnvironmentObject:getEnvironmentObject", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getEnvironmentObject.
type LookupEnvironmentObjectArgs struct {
	// Environment object identifier
	Id string `pulumi:"id"`
}

// A collection of values returned by getEnvironmentObject.
type LookupEnvironmentObjectResult struct {
	// The type of authentication (only used when object*type=METRICS*EXPORT)
	AuthType string `pulumi:"authType"`
	// The ID for the connection auth type (only used when object_type=CONNECTION)
	AuthTypeId string `pulumi:"authTypeId"`
	// Whether to automatically link Deployments to the environment object
	AutoLinkDeployments bool `pulumi:"autoLinkDeployments"`
	// The bearer token to connect to the remote endpoint (only used when object*type=METRICS*EXPORT)
	BasicToken string `pulumi:"basicToken"`
	// The resolved auth type of the connection (only used when object*type=CONNECTION)
	ConnectionAuthType GetEnvironmentObjectConnectionAuthType `pulumi:"connectionAuthType"`
	// Environment Object creation timestamp
	CreatedAt string `pulumi:"createdAt"`
	// Environment Object creator
	CreatedBy GetEnvironmentObjectCreatedBy `pulumi:"createdBy"`
	// The Prometheus endpoint where the metrics are exported (only used when object*type=METRICS*EXPORT)
	Endpoint string `pulumi:"endpoint"`
	// The excluded links for the environment object
	ExcludeLinks []GetEnvironmentObjectExcludeLink `pulumi:"excludeLinks"`
	// The type of exporter (only used when object*type=METRICS*EXPORT)
	ExporterType string `pulumi:"exporterType"`
	// Extra connection details as JSON string (only used when object_type=CONNECTION)
	Extra string `pulumi:"extra"`
	// HTTP request headers for the remote endpoint (only used when object*type=METRICS*EXPORT)
	Headers map[string]string `pulumi:"headers"`
	// The host address for the connection (only used when object_type=CONNECTION)
	Host string `pulumi:"host"`
	// Environment object identifier
	Id string `pulumi:"id"`
	// Whether the value is a secret (only used when object*type=AIRFLOW*VARIABLE)
	IsSecret bool `pulumi:"isSecret"`
	// Key-value pair metrics labels (only used when object*type=METRICS*EXPORT)
	Labels map[string]string `pulumi:"labels"`
	// The Deployments linked to the environment object
	Links []GetEnvironmentObjectLink `pulumi:"links"`
	// The username used for the connection (only used when object_type=CONNECTION)
	Login string `pulumi:"login"`
	// The key for the environment object
	ObjectKey string `pulumi:"objectKey"`
	// The type of environment object (AIRFLOW*VARIABLE, CONNECTION, METRICS*EXPORT)
	ObjectType string `pulumi:"objectType"`
	// The password — the connection password when object*type=CONNECTION, the HTTP Basic-auth password when object*type=METRICS_EXPORT
	Password string `pulumi:"password"`
	// The port for the connection (only used when object_type=CONNECTION)
	Port int `pulumi:"port"`
	// The schema for the connection (only used when object_type=CONNECTION)
	Schema string `pulumi:"schema"`
	// The scope of the environment object (WORKSPACE, DEPLOYMENT)
	Scope string `pulumi:"scope"`
	// The ID of the scope entity where the environment object is created
	ScopeEntityId string `pulumi:"scopeEntityId"`
	// The source scope, if resolved from a link
	SourceScope string `pulumi:"sourceScope"`
	// The source scope entity ID, if resolved from a link
	SourceScopeEntityId string `pulumi:"sourceScopeEntityId"`
	// The connection type (only used when object_type=CONNECTION)
	Type string `pulumi:"type"`
	// Environment Object last updated timestamp
	UpdatedAt string `pulumi:"updatedAt"`
	// Environment Object updater
	UpdatedBy GetEnvironmentObjectUpdatedBy `pulumi:"updatedBy"`
	// The username to connect to the remote endpoint (only used when object*type=METRICS*EXPORT)
	Username string `pulumi:"username"`
	// The value of the Airflow variable (only used when object*type=AIRFLOW*VARIABLE)
	Value string `pulumi:"value"`
}

func LookupEnvironmentObjectOutput(ctx *pulumi.Context, args LookupEnvironmentObjectOutputArgs, opts ...pulumi.InvokeOption) LookupEnvironmentObjectResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupEnvironmentObjectResultOutput, error) {
			args := v.(LookupEnvironmentObjectArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("astronomer:index/getEnvironmentObject:getEnvironmentObject", args, LookupEnvironmentObjectResultOutput{}, options).(LookupEnvironmentObjectResultOutput), nil
		}).(LookupEnvironmentObjectResultOutput)
}

// A collection of arguments for invoking getEnvironmentObject.
type LookupEnvironmentObjectOutputArgs struct {
	// Environment object identifier
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupEnvironmentObjectOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupEnvironmentObjectArgs)(nil)).Elem()
}

// A collection of values returned by getEnvironmentObject.
type LookupEnvironmentObjectResultOutput struct{ *pulumi.OutputState }

func (LookupEnvironmentObjectResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupEnvironmentObjectResult)(nil)).Elem()
}

func (o LookupEnvironmentObjectResultOutput) ToLookupEnvironmentObjectResultOutput() LookupEnvironmentObjectResultOutput {
	return o
}

func (o LookupEnvironmentObjectResultOutput) ToLookupEnvironmentObjectResultOutputWithContext(ctx context.Context) LookupEnvironmentObjectResultOutput {
	return o
}

// The type of authentication (only used when object*type=METRICS*EXPORT)
func (o LookupEnvironmentObjectResultOutput) AuthType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.AuthType }).(pulumi.StringOutput)
}

// The ID for the connection auth type (only used when object_type=CONNECTION)
func (o LookupEnvironmentObjectResultOutput) AuthTypeId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.AuthTypeId }).(pulumi.StringOutput)
}

// Whether to automatically link Deployments to the environment object
func (o LookupEnvironmentObjectResultOutput) AutoLinkDeployments() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) bool { return v.AutoLinkDeployments }).(pulumi.BoolOutput)
}

// The bearer token to connect to the remote endpoint (only used when object*type=METRICS*EXPORT)
func (o LookupEnvironmentObjectResultOutput) BasicToken() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.BasicToken }).(pulumi.StringOutput)
}

// The resolved auth type of the connection (only used when object*type=CONNECTION)
func (o LookupEnvironmentObjectResultOutput) ConnectionAuthType() GetEnvironmentObjectConnectionAuthTypeOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) GetEnvironmentObjectConnectionAuthType {
		return v.ConnectionAuthType
	}).(GetEnvironmentObjectConnectionAuthTypeOutput)
}

// Environment Object creation timestamp
func (o LookupEnvironmentObjectResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Environment Object creator
func (o LookupEnvironmentObjectResultOutput) CreatedBy() GetEnvironmentObjectCreatedByOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) GetEnvironmentObjectCreatedBy { return v.CreatedBy }).(GetEnvironmentObjectCreatedByOutput)
}

// The Prometheus endpoint where the metrics are exported (only used when object*type=METRICS*EXPORT)
func (o LookupEnvironmentObjectResultOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.Endpoint }).(pulumi.StringOutput)
}

// The excluded links for the environment object
func (o LookupEnvironmentObjectResultOutput) ExcludeLinks() GetEnvironmentObjectExcludeLinkArrayOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) []GetEnvironmentObjectExcludeLink { return v.ExcludeLinks }).(GetEnvironmentObjectExcludeLinkArrayOutput)
}

// The type of exporter (only used when object*type=METRICS*EXPORT)
func (o LookupEnvironmentObjectResultOutput) ExporterType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.ExporterType }).(pulumi.StringOutput)
}

// Extra connection details as JSON string (only used when object_type=CONNECTION)
func (o LookupEnvironmentObjectResultOutput) Extra() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.Extra }).(pulumi.StringOutput)
}

// HTTP request headers for the remote endpoint (only used when object*type=METRICS*EXPORT)
func (o LookupEnvironmentObjectResultOutput) Headers() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) map[string]string { return v.Headers }).(pulumi.StringMapOutput)
}

// The host address for the connection (only used when object_type=CONNECTION)
func (o LookupEnvironmentObjectResultOutput) Host() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.Host }).(pulumi.StringOutput)
}

// Environment object identifier
func (o LookupEnvironmentObjectResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.Id }).(pulumi.StringOutput)
}

// Whether the value is a secret (only used when object*type=AIRFLOW*VARIABLE)
func (o LookupEnvironmentObjectResultOutput) GetIsSecret() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) bool { return v.IsSecret }).(pulumi.BoolOutput)
}

// Key-value pair metrics labels (only used when object*type=METRICS*EXPORT)
func (o LookupEnvironmentObjectResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

// The Deployments linked to the environment object
func (o LookupEnvironmentObjectResultOutput) Links() GetEnvironmentObjectLinkArrayOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) []GetEnvironmentObjectLink { return v.Links }).(GetEnvironmentObjectLinkArrayOutput)
}

// The username used for the connection (only used when object_type=CONNECTION)
func (o LookupEnvironmentObjectResultOutput) Login() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.Login }).(pulumi.StringOutput)
}

// The key for the environment object
func (o LookupEnvironmentObjectResultOutput) ObjectKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.ObjectKey }).(pulumi.StringOutput)
}

// The type of environment object (AIRFLOW*VARIABLE, CONNECTION, METRICS*EXPORT)
func (o LookupEnvironmentObjectResultOutput) ObjectType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.ObjectType }).(pulumi.StringOutput)
}

// The password — the connection password when object*type=CONNECTION, the HTTP Basic-auth password when object*type=METRICS_EXPORT
func (o LookupEnvironmentObjectResultOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.Password }).(pulumi.StringOutput)
}

// The port for the connection (only used when object_type=CONNECTION)
func (o LookupEnvironmentObjectResultOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) int { return v.Port }).(pulumi.IntOutput)
}

// The schema for the connection (only used when object_type=CONNECTION)
func (o LookupEnvironmentObjectResultOutput) Schema() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.Schema }).(pulumi.StringOutput)
}

// The scope of the environment object (WORKSPACE, DEPLOYMENT)
func (o LookupEnvironmentObjectResultOutput) Scope() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.Scope }).(pulumi.StringOutput)
}

// The ID of the scope entity where the environment object is created
func (o LookupEnvironmentObjectResultOutput) ScopeEntityId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.ScopeEntityId }).(pulumi.StringOutput)
}

// The source scope, if resolved from a link
func (o LookupEnvironmentObjectResultOutput) SourceScope() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.SourceScope }).(pulumi.StringOutput)
}

// The source scope entity ID, if resolved from a link
func (o LookupEnvironmentObjectResultOutput) SourceScopeEntityId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.SourceScopeEntityId }).(pulumi.StringOutput)
}

// The connection type (only used when object_type=CONNECTION)
func (o LookupEnvironmentObjectResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.Type }).(pulumi.StringOutput)
}

// Environment Object last updated timestamp
func (o LookupEnvironmentObjectResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

// Environment Object updater
func (o LookupEnvironmentObjectResultOutput) UpdatedBy() GetEnvironmentObjectUpdatedByOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) GetEnvironmentObjectUpdatedBy { return v.UpdatedBy }).(GetEnvironmentObjectUpdatedByOutput)
}

// The username to connect to the remote endpoint (only used when object*type=METRICS*EXPORT)
func (o LookupEnvironmentObjectResultOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.Username }).(pulumi.StringOutput)
}

// The value of the Airflow variable (only used when object*type=AIRFLOW*VARIABLE)
func (o LookupEnvironmentObjectResultOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v LookupEnvironmentObjectResult) string { return v.Value }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupEnvironmentObjectResultOutput{})
}
