// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package astronomer

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/ryan-pip/pulumi-astronomer/sdk/go/astronomer/internal"
)

// Notification Channels data source
//
// ## Example Usage
func GetNotificationChannels(ctx *pulumi.Context, args *GetNotificationChannelsArgs, opts ...pulumi.InvokeOption) (*GetNotificationChannelsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetNotificationChannelsResult
	err := ctx.Invoke("astronomer:index/getNotificationChannels:getNotificationChannels", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNotificationChannels.
type GetNotificationChannelsArgs struct {
	ChannelTypes           []string `pulumi:"channelTypes"`
	DeploymentIds          []string `pulumi:"deploymentIds"`
	EntityType             *string  `pulumi:"entityType"`
	NotificationChannelIds []string `pulumi:"notificationChannelIds"`
	WorkspaceIds           []string `pulumi:"workspaceIds"`
}

// A collection of values returned by getNotificationChannels.
type GetNotificationChannelsResult struct {
	ChannelTypes  []string `pulumi:"channelTypes"`
	DeploymentIds []string `pulumi:"deploymentIds"`
	EntityType    *string  `pulumi:"entityType"`
	// The provider-assigned unique ID for this managed resource.
	Id                     string                                       `pulumi:"id"`
	NotificationChannelIds []string                                     `pulumi:"notificationChannelIds"`
	NotificationChannels   []GetNotificationChannelsNotificationChannel `pulumi:"notificationChannels"`
	WorkspaceIds           []string                                     `pulumi:"workspaceIds"`
}

func GetNotificationChannelsOutput(ctx *pulumi.Context, args GetNotificationChannelsOutputArgs, opts ...pulumi.InvokeOption) GetNotificationChannelsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetNotificationChannelsResultOutput, error) {
			args := v.(GetNotificationChannelsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("astronomer:index/getNotificationChannels:getNotificationChannels", args, GetNotificationChannelsResultOutput{}, options).(GetNotificationChannelsResultOutput), nil
		}).(GetNotificationChannelsResultOutput)
}

// A collection of arguments for invoking getNotificationChannels.
type GetNotificationChannelsOutputArgs struct {
	ChannelTypes           pulumi.StringArrayInput `pulumi:"channelTypes"`
	DeploymentIds          pulumi.StringArrayInput `pulumi:"deploymentIds"`
	EntityType             pulumi.StringPtrInput   `pulumi:"entityType"`
	NotificationChannelIds pulumi.StringArrayInput `pulumi:"notificationChannelIds"`
	WorkspaceIds           pulumi.StringArrayInput `pulumi:"workspaceIds"`
}

func (GetNotificationChannelsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNotificationChannelsArgs)(nil)).Elem()
}

// A collection of values returned by getNotificationChannels.
type GetNotificationChannelsResultOutput struct{ *pulumi.OutputState }

func (GetNotificationChannelsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNotificationChannelsResult)(nil)).Elem()
}

func (o GetNotificationChannelsResultOutput) ToGetNotificationChannelsResultOutput() GetNotificationChannelsResultOutput {
	return o
}

func (o GetNotificationChannelsResultOutput) ToGetNotificationChannelsResultOutputWithContext(ctx context.Context) GetNotificationChannelsResultOutput {
	return o
}

func (o GetNotificationChannelsResultOutput) ChannelTypes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetNotificationChannelsResult) []string { return v.ChannelTypes }).(pulumi.StringArrayOutput)
}

func (o GetNotificationChannelsResultOutput) DeploymentIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetNotificationChannelsResult) []string { return v.DeploymentIds }).(pulumi.StringArrayOutput)
}

func (o GetNotificationChannelsResultOutput) EntityType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetNotificationChannelsResult) *string { return v.EntityType }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetNotificationChannelsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNotificationChannelsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetNotificationChannelsResultOutput) NotificationChannelIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetNotificationChannelsResult) []string { return v.NotificationChannelIds }).(pulumi.StringArrayOutput)
}

func (o GetNotificationChannelsResultOutput) NotificationChannels() GetNotificationChannelsNotificationChannelArrayOutput {
	return o.ApplyT(func(v GetNotificationChannelsResult) []GetNotificationChannelsNotificationChannel {
		return v.NotificationChannels
	}).(GetNotificationChannelsNotificationChannelArrayOutput)
}

func (o GetNotificationChannelsResultOutput) WorkspaceIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetNotificationChannelsResult) []string { return v.WorkspaceIds }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNotificationChannelsResultOutput{})
}
