// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package astronomer

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/ryan-pip/pulumi-astronomer/sdk/go/astronomer/internal"
)

// Users data source
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/ryan-pip/pulumi-astronomer/sdk/go/astronomer"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			exampleUsersUsers, err := astronomer.GetUsers(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			_, err = astronomer.GetUsers(ctx, &astronomer.GetUsersArgs{
//				WorkspaceId: pulumi.StringRef("clx42sxw501gl01o0gjenthnh"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = astronomer.GetUsers(ctx, &astronomer.GetUsersArgs{
//				DeploymentId: pulumi.StringRef("clx44jyu001m201m5dzsbexqr"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("exampleUsers", exampleUsersUsers)
//			return nil
//		})
//	}
//
// ```
func GetUsers(ctx *pulumi.Context, args *GetUsersArgs, opts ...pulumi.InvokeOption) (*GetUsersResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetUsersResult
	err := ctx.Invoke("astronomer:index/getUsers:getUsers", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getUsers.
type GetUsersArgs struct {
	DeploymentId *string `pulumi:"deploymentId"`
	WorkspaceId  *string `pulumi:"workspaceId"`
}

// A collection of values returned by getUsers.
type GetUsersResult struct {
	DeploymentId *string `pulumi:"deploymentId"`
	// The provider-assigned unique ID for this managed resource.
	Id          string         `pulumi:"id"`
	Users       []GetUsersUser `pulumi:"users"`
	WorkspaceId *string        `pulumi:"workspaceId"`
}

func GetUsersOutput(ctx *pulumi.Context, args GetUsersOutputArgs, opts ...pulumi.InvokeOption) GetUsersResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetUsersResultOutput, error) {
			args := v.(GetUsersArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv GetUsersResult
			secret, err := ctx.InvokePackageRaw("astronomer:index/getUsers:getUsers", args, &rv, "", opts...)
			if err != nil {
				return GetUsersResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(GetUsersResultOutput)
			if secret {
				return pulumi.ToSecret(output).(GetUsersResultOutput), nil
			}
			return output, nil
		}).(GetUsersResultOutput)
}

// A collection of arguments for invoking getUsers.
type GetUsersOutputArgs struct {
	DeploymentId pulumi.StringPtrInput `pulumi:"deploymentId"`
	WorkspaceId  pulumi.StringPtrInput `pulumi:"workspaceId"`
}

func (GetUsersOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUsersArgs)(nil)).Elem()
}

// A collection of values returned by getUsers.
type GetUsersResultOutput struct{ *pulumi.OutputState }

func (GetUsersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUsersResult)(nil)).Elem()
}

func (o GetUsersResultOutput) ToGetUsersResultOutput() GetUsersResultOutput {
	return o
}

func (o GetUsersResultOutput) ToGetUsersResultOutputWithContext(ctx context.Context) GetUsersResultOutput {
	return o
}

func (o GetUsersResultOutput) DeploymentId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetUsersResult) *string { return v.DeploymentId }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetUsersResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetUsersResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetUsersResultOutput) Users() GetUsersUserArrayOutput {
	return o.ApplyT(func(v GetUsersResult) []GetUsersUser { return v.Users }).(GetUsersUserArrayOutput)
}

func (o GetUsersResultOutput) WorkspaceId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetUsersResult) *string { return v.WorkspaceId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetUsersResultOutput{})
}
