// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/ryan-pip/pulumi-astronomer/sdk/go/astronomer/internal"
)

var _ = internal.GetEnvOrDefault

// Organization id this provider will operate on.
func GetOrganizationId(ctx *pulumi.Context) string {
	return config.Get(ctx, "astronomer:organizationId")
}

// Astronomer API Token. Can be set with an `ASTRONOMER_API_TOKEN` env var.
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "astronomer:token")
}
