// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Outputs
{

    [OutputType]
    public sealed class AlertRules
    {
        /// <summary>
        /// The alert's pattern matches to match against
        /// </summary>
        public readonly ImmutableArray<Outputs.AlertRulesPatternMatch> PatternMatches;
        /// <summary>
        /// The alert's properties used to define the alert
        /// </summary>
        public readonly Outputs.AlertRulesProperties Properties;

        [OutputConstructor]
        private AlertRules(
            ImmutableArray<Outputs.AlertRulesPatternMatch> patternMatches,

            Outputs.AlertRulesProperties properties)
        {
            PatternMatches = patternMatches;
            Properties = properties;
        }
    }
}
