// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Outputs
{

    [OutputType]
    public sealed class AlertsAlerts
    {
        /// <summary>
        /// The entity ID the alert is associated with
        /// </summary>
        public readonly string EntityId;
        /// <summary>
        /// The type of entity the alert is scoped to
        /// </summary>
        public readonly string EntityType;
        /// <summary>
        /// Alert identifier
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// Alert name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Set of notification channel identifiers to notify when the alert is triggered
        /// </summary>
        public readonly ImmutableArray<string> NotificationChannelIds;
        /// <summary>
        /// Alert rules defining the conditions for triggering the alert
        /// </summary>
        public readonly Outputs.AlertsAlertsRules Rules;
        /// <summary>
        /// The alert's severity
        /// </summary>
        public readonly string Severity;
        /// <summary>
        /// The alert's type
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private AlertsAlerts(
            string entityId,

            string entityType,

            string? id,

            string name,

            ImmutableArray<string> notificationChannelIds,

            Outputs.AlertsAlertsRules rules,

            string severity,

            string type)
        {
            EntityId = entityId;
            EntityType = entityType;
            Id = id;
            Name = name;
            NotificationChannelIds = notificationChannelIds;
            Rules = rules;
            Severity = severity;
            Type = type;
        }
    }
}
