// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Outputs
{

    [OutputType]
    public sealed class DeploymentScalingStatus
    {
        public readonly Outputs.DeploymentScalingStatusHibernationStatus? HibernationStatus;

        [OutputConstructor]
        private DeploymentScalingStatus(Outputs.DeploymentScalingStatusHibernationStatus? hibernationStatus)
        {
            HibernationStatus = hibernationStatus;
        }
    }
}
