// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Outputs
{

    [OutputType]
    public sealed class DeploymentEnvironmentVariable
    {
        /// <summary>
        /// Whether the environment variable is a secret.
        /// </summary>
        public readonly bool IsSecret;
        /// <summary>
        /// The environment variable key, used to call the value in code.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// The environment variable value.
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private DeploymentEnvironmentVariable(
            bool isSecret,

            string key,

            string? value)
        {
            IsSecret = isSecret;
            Key = key;
            Value = value;
        }
    }
}
