// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Outputs
{

    [OutputType]
    public sealed class DeploymentWorkerQueue
    {
        public readonly string AstroMachine;
        public readonly string? Id;
        public readonly bool IsDefault;
        public readonly int MaxWorkerCount;
        public readonly int MinWorkerCount;
        public readonly string Name;
        public readonly int WorkerConcurrency;

        [OutputConstructor]
        private DeploymentWorkerQueue(
            string astroMachine,

            string? id,

            bool isDefault,

            int maxWorkerCount,

            int minWorkerCount,

            string name,

            int workerConcurrency)
        {
            AstroMachine = astroMachine;
            Id = id;
            IsDefault = isDefault;
            MaxWorkerCount = maxWorkerCount;
            MinWorkerCount = minWorkerCount;
            Name = name;
            WorkerConcurrency = workerConcurrency;
        }
    }
}
