// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Outputs
{

    [OutputType]
    public sealed class GetApiTokensApiTokenRoleResult
    {
        /// <summary>
        /// The Deployment ID for DAG and TAG entity types
        /// </summary>
        public readonly string DeploymentId;
        /// <summary>
        /// The ID of the entity to assign the role to
        /// </summary>
        public readonly string EntityId;
        /// <summary>
        /// The type of entity to assign the role to
        /// </summary>
        public readonly string EntityType;
        /// <summary>
        /// The role to assign to the entity
        /// </summary>
        public readonly string Role;

        [OutputConstructor]
        private GetApiTokensApiTokenRoleResult(
            string deploymentId,

            string entityId,

            string entityType,

            string role)
        {
            DeploymentId = deploymentId;
            EntityId = entityId;
            EntityType = entityType;
            Role = role;
        }
    }
}
