// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Outputs
{

    [OutputType]
    public sealed class GetEnvironmentObjectsEnvironmentObjectConnectionAuthTypeParameterResult
    {
        /// <summary>
        /// The name of the parameter in Airflow
        /// </summary>
        public readonly string AirflowParamName;
        /// <summary>
        /// The data type of the parameter
        /// </summary>
        public readonly string DataType;
        /// <summary>
        /// A description of the parameter
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// An example value for the parameter
        /// </summary>
        public readonly string Example;
        /// <summary>
        /// The UI-friendly name for the parameter
        /// </summary>
        public readonly string FriendlyName;
        /// <summary>
        /// Whether the parameter is included in the extra field
        /// </summary>
        public readonly bool IsInExtra;
        /// <summary>
        /// Whether the parameter is required
        /// </summary>
        public readonly bool IsRequired;
        /// <summary>
        /// Whether the parameter is a secret
        /// </summary>
        public readonly bool IsSecret;
        /// <summary>
        /// A regex pattern that the parameter value must match
        /// </summary>
        public readonly string Pattern;

        [OutputConstructor]
        private GetEnvironmentObjectsEnvironmentObjectConnectionAuthTypeParameterResult(
            string airflowParamName,

            string dataType,

            string description,

            string example,

            string friendlyName,

            bool isInExtra,

            bool isRequired,

            bool isSecret,

            string pattern)
        {
            AirflowParamName = airflowParamName;
            DataType = dataType;
            Description = description;
            Example = example;
            FriendlyName = friendlyName;
            IsInExtra = isInExtra;
            IsRequired = isRequired;
            IsSecret = isSecret;
            Pattern = pattern;
        }
    }
}
