// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Outputs
{

    [OutputType]
    public sealed class GetNotificationChannelDefinitionResult
    {
        /// <summary>
        /// The API key for the notification channel
        /// </summary>
        public readonly string ApiKey;
        /// <summary>
        /// The DAG ID for the notification channel
        /// </summary>
        public readonly string DagId;
        /// <summary>
        /// The deployment API token for the notification channel
        /// </summary>
        public readonly string DeploymentApiToken;
        /// <summary>
        /// The deployment ID for the notification channel
        /// </summary>
        public readonly string DeploymentId;
        /// <summary>
        /// The integration key for the notification channel
        /// </summary>
        public readonly string IntegrationKey;
        /// <summary>
        /// The recipients for the notification channel
        /// </summary>
        public readonly ImmutableArray<string> Recipients;
        /// <summary>
        /// The webhook URL for the notification channel
        /// </summary>
        public readonly string WebhookUrl;

        [OutputConstructor]
        private GetNotificationChannelDefinitionResult(
            string apiKey,

            string dagId,

            string deploymentApiToken,

            string deploymentId,

            string integrationKey,

            ImmutableArray<string> recipients,

            string webhookUrl)
        {
            ApiKey = apiKey;
            DagId = dagId;
            DeploymentApiToken = deploymentApiToken;
            DeploymentId = deploymentId;
            IntegrationKey = integrationKey;
            Recipients = recipients;
            WebhookUrl = webhookUrl;
        }
    }
}
