// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Outputs
{

    [OutputType]
    public sealed class GetUsersUserResult
    {
        /// <summary>
        /// User avatar URL
        /// </summary>
        public readonly string AvatarUrl;
        /// <summary>
        /// User creation timestamp
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The DAG roles assigned to the user
        /// </summary>
        public readonly ImmutableArray<Outputs.GetUsersUserDagRoleResult> DagRoles;
        /// <summary>
        /// The roles assigned to the deployments
        /// </summary>
        public readonly ImmutableArray<Outputs.GetUsersUserDeploymentRoleResult> DeploymentRoles;
        /// <summary>
        /// User full name
        /// </summary>
        public readonly string FullName;
        /// <summary>
        /// User identifier
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The role assigned to the organization
        /// </summary>
        public readonly string OrganizationRole;
        /// <summary>
        /// User status
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// User last updated timestamp
        /// </summary>
        public readonly string UpdatedAt;
        /// <summary>
        /// User username
        /// </summary>
        public readonly string Username;
        /// <summary>
        /// The roles assigned to the workspaces
        /// </summary>
        public readonly ImmutableArray<Outputs.GetUsersUserWorkspaceRoleResult> WorkspaceRoles;

        [OutputConstructor]
        private GetUsersUserResult(
            string avatarUrl,

            string createdAt,

            ImmutableArray<Outputs.GetUsersUserDagRoleResult> dagRoles,

            ImmutableArray<Outputs.GetUsersUserDeploymentRoleResult> deploymentRoles,

            string fullName,

            string id,

            string organizationRole,

            string status,

            string updatedAt,

            string username,

            ImmutableArray<Outputs.GetUsersUserWorkspaceRoleResult> workspaceRoles)
        {
            AvatarUrl = avatarUrl;
            CreatedAt = createdAt;
            DagRoles = dagRoles;
            DeploymentRoles = deploymentRoles;
            FullName = fullName;
            Id = id;
            OrganizationRole = organizationRole;
            Status = status;
            UpdatedAt = updatedAt;
            Username = username;
            WorkspaceRoles = workspaceRoles;
        }
    }
}
