// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ClusterK8sTag {
    /**
     * The tag's key.
     */
    key: pulumi.Input<string>;
    /**
     * The tag's value.
     */
    value: pulumi.Input<string>;
}

export interface ClusterMetadata {
    externalIps?: pulumi.Input<pulumi.Input<string>[]>;
    oidcIssuerUrl?: pulumi.Input<string>;
}

export interface ClusterNodePool {
    /**
     * Whether the node pool is the default node pool of the cluster.
     */
    isDefault?: pulumi.Input<boolean>;
    /**
     * The maximum number of nodes that can be created in the node pool.
     */
    maxNodeCount: pulumi.Input<number>;
    /**
     * The name of the node pool.
     */
    name: pulumi.Input<string>;
    /**
     * The type of node instance that is used for the node pool.
     */
    nodeInstanceType: pulumi.Input<string>;
}

export interface DeploymentEnvironmentVariable {
    /**
     * Whether the environment variable is a secret.
     */
    isSecret: pulumi.Input<boolean>;
    /**
     * The environment variable key, used to call the value in code.
     */
    key: pulumi.Input<string>;
    /**
     * The environment variable value.
     */
    value?: pulumi.Input<string>;
}

export interface DeploymentWorkerQueue {
    astroMachine: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    isDefault: pulumi.Input<boolean>;
    maxWorkerCount: pulumi.Input<number>;
    minWorkerCount: pulumi.Input<number>;
    name: pulumi.Input<string>;
    workerConcurrency: pulumi.Input<number>;
}

