// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AlertCreatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface AlertNotificationChannel {
    /**
     * Notification Channel creation timestamp
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Notification Channel creator
     */
    createdBy?: pulumi.Input<inputs.AlertNotificationChannelCreatedBy>;
    /**
     * The notification channel's definition
     */
    definition: pulumi.Input<inputs.AlertNotificationChannelDefinition>;
    /**
     * The deployment ID the notification channel is scoped to
     */
    deploymentId?: pulumi.Input<string>;
    /**
     * The entity ID the notification channel is scoped to
     */
    entityId: pulumi.Input<string>;
    /**
     * The name of the entity the notification channel is scoped to
     */
    entityName?: pulumi.Input<string>;
    /**
     * The type of entity the notification channel is scoped to (e.g., 'DEPLOYMENT')
     */
    entityType: pulumi.Input<string>;
    /**
     * The notification channel's ID
     */
    id?: pulumi.Input<string>;
    /**
     * When entity type is scoped to ORGANIZATION or WORKSPACE, this determines if child entities can access this notification channel.
     */
    isShared?: pulumi.Input<boolean>;
    /**
     * The notification channel's name
     */
    name: pulumi.Input<string>;
    /**
     * The notification channel's type
     */
    type: pulumi.Input<string>;
    /**
     * Notification Channel last updated timestamp
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * Notification Channel updater
     */
    updatedBy?: pulumi.Input<inputs.AlertNotificationChannelUpdatedBy>;
    /**
     * The workspace ID the notification channel is scoped to
     */
    workspaceId?: pulumi.Input<string>;
}

export interface AlertNotificationChannelCreatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface AlertNotificationChannelDefinition {
    /**
     * The API key for the notification channel
     */
    apiKey?: pulumi.Input<string>;
    /**
     * The DAG ID for the notification channel
     */
    dagId?: pulumi.Input<string>;
    /**
     * The deployment API token for the notification channel
     */
    deploymentApiToken?: pulumi.Input<string>;
    /**
     * The deployment ID for the notification channel
     */
    deploymentId?: pulumi.Input<string>;
    /**
     * The integration key for the notification channel
     */
    integrationKey?: pulumi.Input<string>;
    /**
     * The recipients for the notification channel
     */
    recipients?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The webhook URL for the notification channel
     */
    webhookUrl?: pulumi.Input<string>;
}

export interface AlertNotificationChannelUpdatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface AlertRules {
    /**
     * The alert's pattern matches to match against
     */
    patternMatches: pulumi.Input<pulumi.Input<inputs.AlertRulesPatternMatch>[]>;
    /**
     * The alert's properties used to define the alert
     */
    properties: pulumi.Input<inputs.AlertRulesProperties>;
}

export interface AlertRulesPatternMatch {
    /**
     * The type of entity to match against
     */
    entityType: pulumi.Input<string>;
    /**
     * The type of operator to use for the pattern match
     */
    operatorType: pulumi.Input<string>;
    /**
     * The values to match against
     */
    values: pulumi.Input<pulumi.Input<string>[]>;
}

export interface AlertRulesProperties {
    /**
     * The deadline for the DAG in HH:MM 24-hour UTC format
     */
    dagDeadline?: pulumi.Input<string>;
    /**
     * The duration of the DAG in seconds (minimum 60)
     */
    dagDurationSeconds?: pulumi.Input<number>;
    /**
     * The days of the week for the timeliness rule
     */
    daysOfWeeks?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The ID of the deployment for the alert rule
     */
    deploymentId: pulumi.Input<string>;
    /**
     * The look-back period in seconds (minimum 60)
     */
    lookBackPeriodSeconds?: pulumi.Input<number>;
    /**
     * The duration of the Task in seconds (minimum 60)
     */
    taskDurationSeconds?: pulumi.Input<number>;
}

export interface AlertUpdatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface ApiTokenCreatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface ApiTokenRole {
    /**
     * The Deployment ID. Required for DAG and TAG entity types.
     */
    deploymentId?: pulumi.Input<string>;
    /**
     * The ID of the entity to assign the role to. For DAG entity type, this is the dag_id. For TAG entity type, this is the tag value.
     */
    entityId: pulumi.Input<string>;
    /**
     * The type of entity to assign the role to
     */
    entityType: pulumi.Input<string>;
    /**
     * The role to assign to the entity
     */
    role: pulumi.Input<string>;
}

export interface ApiTokenUpdatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface ClusterHealthStatus {
    /**
     * Cluster health status details
     */
    details?: pulumi.Input<pulumi.Input<inputs.ClusterHealthStatusDetail>[]>;
    /**
     * Cluster health status value
     */
    value?: pulumi.Input<string>;
}

export interface ClusterHealthStatusDetail {
    /**
     * Cluster health status detail code
     */
    code?: pulumi.Input<string>;
    /**
     * Cluster health status detail description
     */
    description?: pulumi.Input<string>;
    /**
     * Cluster health status detail severity
     */
    severity?: pulumi.Input<string>;
}

export interface ClusterMetadata {
    /**
     * Cluster external IPs
     */
    externalIps?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Cluster kube DNS IP
     */
    kubeDnsIp?: pulumi.Input<string>;
    /**
     * Cluster OIDC issuer URL
     */
    oidcIssuerUrl?: pulumi.Input<string>;
}

export interface ClusterNodePool {
    /**
     * Node pool cloud provider. Allowed values: `AWS`, `GCP`, `AZURE`.
     */
    cloudProvider?: pulumi.Input<string>;
    /**
     * Node pool cluster identifier
     */
    clusterId?: pulumi.Input<string>;
    /**
     * Node pool creation timestamp
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Node pool identifier
     */
    id?: pulumi.Input<string>;
    /**
     * Whether the node pool is the default node pool of the cluster
     */
    isDefault?: pulumi.Input<boolean>;
    /**
     * Node pool maximum node count
     */
    maxNodeCount?: pulumi.Input<number>;
    /**
     * Node pool name
     */
    name?: pulumi.Input<string>;
    /**
     * Node pool node instance type
     */
    nodeInstanceType?: pulumi.Input<string>;
    /**
     * Node pool supported Astro machines
     */
    supportedAstroMachines?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Node pool last updated timestamp
     */
    updatedAt?: pulumi.Input<string>;
}

export interface ClusterTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    update?: pulumi.Input<string>;
}

export interface CustomRoleCreatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface CustomRoleUpdatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface DeploymentCreatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface DeploymentEnvironmentVariable {
    /**
     * Whether Environment variable is a secret
     */
    isSecret: pulumi.Input<boolean>;
    /**
     * Environment variable key
     */
    key: pulumi.Input<string>;
    /**
     * Environment variable last updated timestamp
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * Environment variable value
     */
    value?: pulumi.Input<string>;
}

export interface DeploymentRemoteExecution {
    /**
     * The allowed IP address ranges for remote execution
     */
    allowedIpAddressRanges?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether remote execution is enabled
     */
    enabled: pulumi.Input<boolean>;
    /**
     * The URL for the remote API
     */
    remoteApiUrl?: pulumi.Input<string>;
    /**
     * The bucket for task logs
     */
    taskLogBucket?: pulumi.Input<string>;
    /**
     * The URL pattern for task logs
     */
    taskLogUrlPattern?: pulumi.Input<string>;
}

export interface DeploymentScalingSpec {
    /**
     * Hibernation configuration for the deployment. The deployment will hibernate according to the schedules defined in this configuration. To remove the hibernation configuration, set scaling*spec to null.
     */
    hibernationSpec: pulumi.Input<inputs.DeploymentScalingSpecHibernationSpec>;
}

export interface DeploymentScalingSpecHibernationSpec {
    /**
     * Hibernation override configuration. Set to null to remove the override.
     */
    override?: pulumi.Input<inputs.DeploymentScalingSpecHibernationSpecOverride>;
    /**
     * List of hibernation schedules. Set to null to remove all schedules.
     */
    schedules?: pulumi.Input<pulumi.Input<inputs.DeploymentScalingSpecHibernationSpecSchedule>[]>;
}

export interface DeploymentScalingSpecHibernationSpecOverride {
    isActive?: pulumi.Input<boolean>;
    isHibernating: pulumi.Input<boolean>;
    overrideUntil?: pulumi.Input<string>;
}

export interface DeploymentScalingSpecHibernationSpecSchedule {
    description?: pulumi.Input<string>;
    hibernateAtCron: pulumi.Input<string>;
    isEnabled: pulumi.Input<boolean>;
    wakeAtCron: pulumi.Input<string>;
}

export interface DeploymentScalingStatus {
    hibernationStatus?: pulumi.Input<inputs.DeploymentScalingStatusHibernationStatus>;
}

export interface DeploymentScalingStatusHibernationStatus {
    isHibernating?: pulumi.Input<boolean>;
    nextEventAt?: pulumi.Input<string>;
    nextEventType?: pulumi.Input<string>;
    reason?: pulumi.Input<string>;
}

export interface DeploymentUpdatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface DeploymentWorkerQueue {
    /**
     * Worker queue Astro machine value - required for 'STANDARD' and 'DEDICATED' deployments. Allowed values: `A5`, `A10`, `A20`, `A40`, `A60`, `A120`, `A160`.
     */
    astroMachine?: pulumi.Input<string>;
    /**
     * Worker queue default
     */
    isDefault: pulumi.Input<boolean>;
    /**
     * Worker queue max worker count
     */
    maxWorkerCount: pulumi.Input<number>;
    /**
     * Worker queue min worker count
     */
    minWorkerCount: pulumi.Input<number>;
    /**
     * Worker queue name
     */
    name: pulumi.Input<string>;
    /**
     * Worker queue Node pool identifier - required for 'HYBRID' deployments
     */
    nodePoolId?: pulumi.Input<string>;
    /**
     * Worker queue pod CPU
     */
    podCpu?: pulumi.Input<string>;
    /**
     * Worker queue pod memory
     */
    podMemory?: pulumi.Input<string>;
    /**
     * Worker queue worker concurrency
     */
    workerConcurrency: pulumi.Input<number>;
}

export interface NotificationChannelCreatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface NotificationChannelDefinition {
    /**
     * The API key for the notification channel
     */
    apiKey?: pulumi.Input<string>;
    /**
     * The DAG ID for the notification channel
     */
    dagId?: pulumi.Input<string>;
    /**
     * The deployment API token for the notification channel
     */
    deploymentApiToken?: pulumi.Input<string>;
    /**
     * The deployment ID for the notification channel
     */
    deploymentId?: pulumi.Input<string>;
    /**
     * The integration key for the notification channel
     */
    integrationKey?: pulumi.Input<string>;
    /**
     * The recipients for the notification channel
     */
    recipients?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The webhook URL for the notification channel
     */
    webhookUrl?: pulumi.Input<string>;
}

export interface NotificationChannelUpdatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface TeamCreatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface TeamDagRole {
    /**
     * The DAG ID. Required if tag is not specified.
     */
    dagId?: pulumi.Input<string>;
    /**
     * The Deployment ID containing the DAG.
     */
    deploymentId: pulumi.Input<string>;
    /**
     * The DAG role (DAG*VIEWER, DAG*AUTHOR, or custom DAG role).
     */
    role: pulumi.Input<string>;
    /**
     * The DAG tag. Required if dagId is not specified.
     */
    tag?: pulumi.Input<string>;
}

export interface TeamDeploymentRole {
    /**
     * The ID of the deployment to assign the role to
     */
    deploymentId: pulumi.Input<string>;
    /**
     * The role to assign to the deployment
     */
    role: pulumi.Input<string>;
}

export interface TeamRolesDagRole {
    /**
     * The DAG ID. Required if tag is not specified.
     */
    dagId?: pulumi.Input<string>;
    /**
     * The Deployment ID containing the DAG.
     */
    deploymentId: pulumi.Input<string>;
    /**
     * The DAG role (DAG*VIEWER, DAG*AUTHOR, or custom DAG role).
     */
    role: pulumi.Input<string>;
    /**
     * The DAG tag. Required if dagId is not specified.
     */
    tag?: pulumi.Input<string>;
}

export interface TeamRolesDeploymentRole {
    /**
     * The ID of the deployment to assign the role to
     */
    deploymentId: pulumi.Input<string>;
    /**
     * The role to assign to the deployment
     */
    role: pulumi.Input<string>;
}

export interface TeamRolesWorkspaceRole {
    /**
     * The role to assign to the workspace
     */
    role: pulumi.Input<string>;
    /**
     * The ID of the workspace to assign the role to
     */
    workspaceId: pulumi.Input<string>;
}

export interface TeamUpdatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface TeamWorkspaceRole {
    /**
     * The role to assign to the workspace
     */
    role: pulumi.Input<string>;
    /**
     * The ID of the workspace to assign the role to
     */
    workspaceId: pulumi.Input<string>;
}

export interface UserInviteInvitee {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface UserInviteInviter {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface UserRolesDagRole {
    /**
     * The DAG ID. Required if tag is not specified.
     */
    dagId?: pulumi.Input<string>;
    /**
     * The Deployment ID containing the DAG.
     */
    deploymentId: pulumi.Input<string>;
    /**
     * The DAG role (DAG*VIEWER, DAG*AUTHOR, or custom DAG role).
     */
    role: pulumi.Input<string>;
    /**
     * The DAG tag. Required if dagId is not specified.
     */
    tag?: pulumi.Input<string>;
}

export interface UserRolesDeploymentRole {
    /**
     * The ID of the deployment to assign the role to
     */
    deploymentId: pulumi.Input<string>;
    /**
     * The role to assign to the deployment
     */
    role: pulumi.Input<string>;
}

export interface UserRolesWorkspaceRole {
    /**
     * The role to assign to the workspace
     */
    role: pulumi.Input<string>;
    /**
     * The ID of the workspace to assign the role to
     */
    workspaceId: pulumi.Input<string>;
}

export interface WorkspaceCreatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface WorkspaceUpdatedBy {
    apiTokenName?: pulumi.Input<string>;
    avatarUrl?: pulumi.Input<string>;
    fullName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    subjectType?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}
