// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Inputs
{

    public sealed class AlertRulesArgs : global::Pulumi.ResourceArgs
    {
        [Input("patternMatches", required: true)]
        private InputList<Inputs.AlertRulesPatternMatchArgs>? _patternMatches;

        /// <summary>
        /// The alert's pattern matches to match against
        /// </summary>
        public InputList<Inputs.AlertRulesPatternMatchArgs> PatternMatches
        {
            get => _patternMatches ?? (_patternMatches = new InputList<Inputs.AlertRulesPatternMatchArgs>());
            set => _patternMatches = value;
        }

        /// <summary>
        /// The alert's properties used to define the alert
        /// </summary>
        [Input("properties", required: true)]
        public Input<Inputs.AlertRulesPropertiesArgs> Properties { get; set; } = null!;

        public AlertRulesArgs()
        {
        }
        public static new AlertRulesArgs Empty => new AlertRulesArgs();
    }
}
