// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Inputs
{

    public sealed class AlertNotificationChannelDefinitionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiKey")]
        private Input<string>? _apiKey;

        /// <summary>
        /// The API key for the notification channel
        /// </summary>
        public Input<string>? ApiKey
        {
            get => _apiKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _apiKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The DAG ID for the notification channel
        /// </summary>
        [Input("dagId")]
        public Input<string>? DagId { get; set; }

        [Input("deploymentApiToken")]
        private Input<string>? _deploymentApiToken;

        /// <summary>
        /// The deployment API token for the notification channel
        /// </summary>
        public Input<string>? DeploymentApiToken
        {
            get => _deploymentApiToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _deploymentApiToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The deployment ID for the notification channel
        /// </summary>
        [Input("deploymentId")]
        public Input<string>? DeploymentId { get; set; }

        [Input("integrationKey")]
        private Input<string>? _integrationKey;

        /// <summary>
        /// The integration key for the notification channel
        /// </summary>
        public Input<string>? IntegrationKey
        {
            get => _integrationKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _integrationKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("recipients")]
        private InputList<string>? _recipients;

        /// <summary>
        /// The recipients for the notification channel
        /// </summary>
        public InputList<string> Recipients
        {
            get => _recipients ?? (_recipients = new InputList<string>());
            set => _recipients = value;
        }

        [Input("webhookUrl")]
        private Input<string>? _webhookUrl;

        /// <summary>
        /// The webhook URL for the notification channel
        /// </summary>
        public Input<string>? WebhookUrl
        {
            get => _webhookUrl;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _webhookUrl = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public AlertNotificationChannelDefinitionGetArgs()
        {
        }
        public static new AlertNotificationChannelDefinitionGetArgs Empty => new AlertNotificationChannelDefinitionGetArgs();
    }
}
