// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Inputs
{

    public sealed class ClusterHealthStatusGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("details")]
        private InputList<Inputs.ClusterHealthStatusDetailGetArgs>? _details;

        /// <summary>
        /// Cluster health status details
        /// </summary>
        public InputList<Inputs.ClusterHealthStatusDetailGetArgs> Details
        {
            get => _details ?? (_details = new InputList<Inputs.ClusterHealthStatusDetailGetArgs>());
            set => _details = value;
        }

        /// <summary>
        /// Cluster health status value
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public ClusterHealthStatusGetArgs()
        {
        }
        public static new ClusterHealthStatusGetArgs Empty => new ClusterHealthStatusGetArgs();
    }
}
