// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Inputs
{

    public sealed class ClusterMetadataGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("externalIps")]
        private InputList<string>? _externalIps;
        public InputList<string> ExternalIps
        {
            get => _externalIps ?? (_externalIps = new InputList<string>());
            set => _externalIps = value;
        }

        [Input("oidcIssuerUrl")]
        public Input<string>? OidcIssuerUrl { get; set; }

        public ClusterMetadataGetArgs()
        {
        }
        public static new ClusterMetadataGetArgs Empty => new ClusterMetadataGetArgs();
    }
}
