// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Inputs
{

    public sealed class DeploymentRemoteExecutionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowedIpAddressRanges")]
        private InputList<string>? _allowedIpAddressRanges;

        /// <summary>
        /// The allowed IP address ranges for remote execution
        /// </summary>
        public InputList<string> AllowedIpAddressRanges
        {
            get => _allowedIpAddressRanges ?? (_allowedIpAddressRanges = new InputList<string>());
            set => _allowedIpAddressRanges = value;
        }

        /// <summary>
        /// Whether remote execution is enabled
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// The URL for the remote API
        /// </summary>
        [Input("remoteApiUrl")]
        public Input<string>? RemoteApiUrl { get; set; }

        /// <summary>
        /// The bucket for task logs
        /// </summary>
        [Input("taskLogBucket")]
        public Input<string>? TaskLogBucket { get; set; }

        /// <summary>
        /// The URL pattern for task logs
        /// </summary>
        [Input("taskLogUrlPattern")]
        public Input<string>? TaskLogUrlPattern { get; set; }

        public DeploymentRemoteExecutionGetArgs()
        {
        }
        public static new DeploymentRemoteExecutionGetArgs Empty => new DeploymentRemoteExecutionGetArgs();
    }
}
