// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Inputs
{

    public sealed class EnvironmentObjectConnectionAuthTypeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The type of connection in Airflow
        /// </summary>
        [Input("airflowType")]
        public Input<string>? AirflowType { get; set; }

        /// <summary>
        /// The name of the auth method used in the connection
        /// </summary>
        [Input("authMethodName")]
        public Input<string>? AuthMethodName { get; set; }

        /// <summary>
        /// A description of the connection auth type
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The URL to the guide for the connection auth type
        /// </summary>
        [Input("guidePath")]
        public Input<string>? GuidePath { get; set; }

        /// <summary>
        /// The ID of the connection auth type
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The name of the connection auth type
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("parameters")]
        private InputList<Inputs.EnvironmentObjectConnectionAuthTypeParameterArgs>? _parameters;

        /// <summary>
        /// The parameters for the connection auth type
        /// </summary>
        public InputList<Inputs.EnvironmentObjectConnectionAuthTypeParameterArgs> Parameters
        {
            get => _parameters ?? (_parameters = new InputList<Inputs.EnvironmentObjectConnectionAuthTypeParameterArgs>());
            set => _parameters = value;
        }

        /// <summary>
        /// The URL of the provider logo
        /// </summary>
        [Input("providerLogo")]
        public Input<string>? ProviderLogo { get; set; }

        /// <summary>
        /// The name of the provider package
        /// </summary>
        [Input("providerPackageName")]
        public Input<string>? ProviderPackageName { get; set; }

        public EnvironmentObjectConnectionAuthTypeArgs()
        {
        }
        public static new EnvironmentObjectConnectionAuthTypeArgs Empty => new EnvironmentObjectConnectionAuthTypeArgs();
    }
}
