// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Inputs
{

    public sealed class EnvironmentObjectLinkArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Per-link overrides. Set only the fields matching the parent object_type.
        /// </summary>
        [Input("overrides")]
        public Input<Inputs.EnvironmentObjectLinkOverridesArgs>? Overrides { get; set; }

        /// <summary>
        /// Scope of the linked entity (DEPLOYMENT)
        /// </summary>
        [Input("scope", required: true)]
        public Input<string> Scope { get; set; } = null!;

        /// <summary>
        /// Linked entity ID
        /// </summary>
        [Input("scopeEntityId", required: true)]
        public Input<string> ScopeEntityId { get; set; } = null!;

        public EnvironmentObjectLinkArgs()
        {
        }
        public static new EnvironmentObjectLinkArgs Empty => new EnvironmentObjectLinkArgs();
    }
}
