// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RyanPip.Astronomer.Inputs
{

    public sealed class EnvironmentObjectExcludeLinkGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Scope of the excluded entity (DEPLOYMENT)
        /// </summary>
        [Input("scope", required: true)]
        public Input<string> Scope { get; set; } = null!;

        /// <summary>
        /// ID of the excluded entity
        /// </summary>
        [Input("scopeEntityId", required: true)]
        public Input<string> ScopeEntityId { get; set; } = null!;

        public EnvironmentObjectExcludeLinkGetArgs()
        {
        }
        public static new EnvironmentObjectExcludeLinkGetArgs Empty => new EnvironmentObjectExcludeLinkGetArgs();
    }
}
