// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Alert resource
 */
export class Alert extends pulumi.CustomResource {
    /**
     * Get an existing Alert resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AlertState, opts?: pulumi.CustomResourceOptions): Alert {
        return new Alert(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'astronomer:index/alert:Alert';

    /**
     * Returns true if the given object is an instance of Alert.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Alert {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Alert.__pulumiType;
    }

    /**
     * Alert creation timestamp
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Alert creator
     */
    declare public /*out*/ readonly createdBy: pulumi.Output<outputs.AlertCreatedBy>;
    /**
     * The ID of the Deployment to which the alert is scoped
     */
    declare public /*out*/ readonly deploymentId: pulumi.Output<string>;
    /**
     * The entity ID the alert is associated with
     */
    declare public readonly entityId: pulumi.Output<string>;
    /**
     * The name of the entity the alert is associated with
     */
    declare public /*out*/ readonly entityName: pulumi.Output<string>;
    /**
     * The ID of the Deployment to which the alert is scoped
     */
    declare public readonly entityType: pulumi.Output<string>;
    /**
     * Alert name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Set of notification channel identifiers to notify when the alert is triggered
     */
    declare public readonly notificationChannelIds: pulumi.Output<string[]>;
    /**
     * The notification channels to send alerts to
     */
    declare public /*out*/ readonly notificationChannels: pulumi.Output<outputs.AlertNotificationChannel[]>;
    /**
     * Alert rules defining the conditions for triggering the alert
     */
    declare public readonly rules: pulumi.Output<outputs.AlertRules>;
    /**
     * The alert's severity
     */
    declare public readonly severity: pulumi.Output<string>;
    /**
     * The alert's type
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * Alert last updated timestamp
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * Alert updater
     */
    declare public /*out*/ readonly updatedBy: pulumi.Output<outputs.AlertUpdatedBy>;
    /**
     * The ID of the Workspace to which the alert is scoped
     */
    declare public /*out*/ readonly workspaceId: pulumi.Output<string>;

    /**
     * Create a Alert resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AlertArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AlertArgs | AlertState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AlertState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["createdBy"] = state?.createdBy;
            resourceInputs["deploymentId"] = state?.deploymentId;
            resourceInputs["entityId"] = state?.entityId;
            resourceInputs["entityName"] = state?.entityName;
            resourceInputs["entityType"] = state?.entityType;
            resourceInputs["name"] = state?.name;
            resourceInputs["notificationChannelIds"] = state?.notificationChannelIds;
            resourceInputs["notificationChannels"] = state?.notificationChannels;
            resourceInputs["rules"] = state?.rules;
            resourceInputs["severity"] = state?.severity;
            resourceInputs["type"] = state?.type;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["updatedBy"] = state?.updatedBy;
            resourceInputs["workspaceId"] = state?.workspaceId;
        } else {
            const args = argsOrState as AlertArgs | undefined;
            if (args?.entityId === undefined && !opts.urn) {
                throw new Error("Missing required property 'entityId'");
            }
            if (args?.entityType === undefined && !opts.urn) {
                throw new Error("Missing required property 'entityType'");
            }
            if (args?.notificationChannelIds === undefined && !opts.urn) {
                throw new Error("Missing required property 'notificationChannelIds'");
            }
            if (args?.rules === undefined && !opts.urn) {
                throw new Error("Missing required property 'rules'");
            }
            if (args?.severity === undefined && !opts.urn) {
                throw new Error("Missing required property 'severity'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["entityId"] = args?.entityId;
            resourceInputs["entityType"] = args?.entityType;
            resourceInputs["name"] = args?.name;
            resourceInputs["notificationChannelIds"] = args?.notificationChannelIds;
            resourceInputs["rules"] = args?.rules;
            resourceInputs["severity"] = args?.severity;
            resourceInputs["type"] = args?.type;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["createdBy"] = undefined /*out*/;
            resourceInputs["deploymentId"] = undefined /*out*/;
            resourceInputs["entityName"] = undefined /*out*/;
            resourceInputs["notificationChannels"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["updatedBy"] = undefined /*out*/;
            resourceInputs["workspaceId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Alert.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Alert resources.
 */
export interface AlertState {
    /**
     * Alert creation timestamp
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Alert creator
     */
    createdBy?: pulumi.Input<inputs.AlertCreatedBy>;
    /**
     * The ID of the Deployment to which the alert is scoped
     */
    deploymentId?: pulumi.Input<string>;
    /**
     * The entity ID the alert is associated with
     */
    entityId?: pulumi.Input<string>;
    /**
     * The name of the entity the alert is associated with
     */
    entityName?: pulumi.Input<string>;
    /**
     * The ID of the Deployment to which the alert is scoped
     */
    entityType?: pulumi.Input<string>;
    /**
     * Alert name
     */
    name?: pulumi.Input<string>;
    /**
     * Set of notification channel identifiers to notify when the alert is triggered
     */
    notificationChannelIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The notification channels to send alerts to
     */
    notificationChannels?: pulumi.Input<pulumi.Input<inputs.AlertNotificationChannel>[]>;
    /**
     * Alert rules defining the conditions for triggering the alert
     */
    rules?: pulumi.Input<inputs.AlertRules>;
    /**
     * The alert's severity
     */
    severity?: pulumi.Input<string>;
    /**
     * The alert's type
     */
    type?: pulumi.Input<string>;
    /**
     * Alert last updated timestamp
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * Alert updater
     */
    updatedBy?: pulumi.Input<inputs.AlertUpdatedBy>;
    /**
     * The ID of the Workspace to which the alert is scoped
     */
    workspaceId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Alert resource.
 */
export interface AlertArgs {
    /**
     * The entity ID the alert is associated with
     */
    entityId: pulumi.Input<string>;
    /**
     * The ID of the Deployment to which the alert is scoped
     */
    entityType: pulumi.Input<string>;
    /**
     * Alert name
     */
    name?: pulumi.Input<string>;
    /**
     * Set of notification channel identifiers to notify when the alert is triggered
     */
    notificationChannelIds: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Alert rules defining the conditions for triggering the alert
     */
    rules: pulumi.Input<inputs.AlertRules>;
    /**
     * The alert's severity
     */
    severity: pulumi.Input<string>;
    /**
     * The alert's type
     */
    type: pulumi.Input<string>;
}
