// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Alerts data source
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as astronomer from "@ryan-pip/pulumi_astronomer";
 *
 * const exampleAlerts = astronomer.getAlerts({});
 * const alertIdsExample = astronomer.getAlerts({
 *     alertIds: ["cm4ntm56001gk01mbhudv1elv"],
 * });
 * const workspaceIdsExample = astronomer.getAlerts({
 *     workspaceIds: ["clx42sxw501gl01o0gjenthnh"],
 * });
 * const deploymentIdsExample = astronomer.getAlerts({
 *     deploymentIds: ["clx44jyu001m201m5dzsbexqr"],
 * });
 * const alertTypesExample = astronomer.getAlerts({
 *     alertTypes: [
 *         "DAG_FAILURE",
 *         "DAG_SUCCESS",
 *     ],
 * });
 * const entityTypeExample = astronomer.getAlerts({
 *     entityType: "DEPLOYMENT",
 * });
 * export const alerts = exampleAlerts;
 * ```
 */
export function getAlerts(args?: GetAlertsArgs, opts?: pulumi.InvokeOptions): Promise<GetAlertsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("astronomer:index/getAlerts:getAlerts", {
        "alertIds": args.alertIds,
        "alertTypes": args.alertTypes,
        "deploymentIds": args.deploymentIds,
        "entityType": args.entityType,
        "workspaceIds": args.workspaceIds,
    }, opts);
}

/**
 * A collection of arguments for invoking getAlerts.
 */
export interface GetAlertsArgs {
    alertIds?: string[];
    alertTypes?: string[];
    deploymentIds?: string[];
    entityType?: string;
    workspaceIds?: string[];
}

/**
 * A collection of values returned by getAlerts.
 */
export interface GetAlertsResult {
    readonly alertIds?: string[];
    readonly alertTypes?: string[];
    readonly alerts: outputs.GetAlertsAlert[];
    readonly deploymentIds?: string[];
    readonly entityType?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly workspaceIds?: string[];
}
/**
 * Alerts data source
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as astronomer from "@ryan-pip/pulumi_astronomer";
 *
 * const exampleAlerts = astronomer.getAlerts({});
 * const alertIdsExample = astronomer.getAlerts({
 *     alertIds: ["cm4ntm56001gk01mbhudv1elv"],
 * });
 * const workspaceIdsExample = astronomer.getAlerts({
 *     workspaceIds: ["clx42sxw501gl01o0gjenthnh"],
 * });
 * const deploymentIdsExample = astronomer.getAlerts({
 *     deploymentIds: ["clx44jyu001m201m5dzsbexqr"],
 * });
 * const alertTypesExample = astronomer.getAlerts({
 *     alertTypes: [
 *         "DAG_FAILURE",
 *         "DAG_SUCCESS",
 *     ],
 * });
 * const entityTypeExample = astronomer.getAlerts({
 *     entityType: "DEPLOYMENT",
 * });
 * export const alerts = exampleAlerts;
 * ```
 */
export function getAlertsOutput(args?: GetAlertsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAlertsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("astronomer:index/getAlerts:getAlerts", {
        "alertIds": args.alertIds,
        "alertTypes": args.alertTypes,
        "deploymentIds": args.deploymentIds,
        "entityType": args.entityType,
        "workspaceIds": args.workspaceIds,
    }, opts);
}

/**
 * A collection of arguments for invoking getAlerts.
 */
export interface GetAlertsOutputArgs {
    alertIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    alertTypes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    deploymentIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    entityType?: pulumi.Input<string | undefined>;
    workspaceIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
