// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Environment Object data source
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as astronomer from "@ryan-pip/pulumi_astronomer";
 *
 * const exampleEnvironmentObject = astronomer.getEnvironmentObject({
 *     id: "cm4ntm56001gk01mbhudv1elv",
 * });
 * export const environmentObject = exampleEnvironmentObject;
 * ```
 */
export function getEnvironmentObject(args: GetEnvironmentObjectArgs, opts?: pulumi.InvokeOptions): Promise<GetEnvironmentObjectResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("astronomer:index/getEnvironmentObject:getEnvironmentObject", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvironmentObject.
 */
export interface GetEnvironmentObjectArgs {
    /**
     * Environment object identifier
     */
    id: string;
}

/**
 * A collection of values returned by getEnvironmentObject.
 */
export interface GetEnvironmentObjectResult {
    /**
     * The type of authentication (only used when object*type=METRICS*EXPORT)
     */
    readonly authType: string;
    /**
     * The ID for the connection auth type (only used when object_type=CONNECTION)
     */
    readonly authTypeId: string;
    /**
     * Whether to automatically link Deployments to the environment object
     */
    readonly autoLinkDeployments: boolean;
    /**
     * The bearer token to connect to the remote endpoint (only used when object*type=METRICS*EXPORT)
     */
    readonly basicToken: string;
    /**
     * The resolved auth type of the connection (only used when object*type=CONNECTION)
     */
    readonly connectionAuthType: outputs.GetEnvironmentObjectConnectionAuthType;
    /**
     * Environment Object creation timestamp
     */
    readonly createdAt: string;
    /**
     * Environment Object creator
     */
    readonly createdBy: outputs.GetEnvironmentObjectCreatedBy;
    /**
     * The Prometheus endpoint where the metrics are exported (only used when object*type=METRICS*EXPORT)
     */
    readonly endpoint: string;
    /**
     * The excluded links for the environment object
     */
    readonly excludeLinks: outputs.GetEnvironmentObjectExcludeLink[];
    /**
     * The type of exporter (only used when object*type=METRICS*EXPORT)
     */
    readonly exporterType: string;
    /**
     * Extra connection details as JSON string (only used when object_type=CONNECTION)
     */
    readonly extra: string;
    /**
     * HTTP request headers for the remote endpoint (only used when object*type=METRICS*EXPORT)
     */
    readonly headers: {[key: string]: string};
    /**
     * The host address for the connection (only used when object_type=CONNECTION)
     */
    readonly host: string;
    /**
     * Environment object identifier
     */
    readonly id: string;
    /**
     * Whether the value is a secret (only used when object*type=AIRFLOW*VARIABLE)
     */
    readonly isSecret: boolean;
    /**
     * Key-value pair metrics labels (only used when object*type=METRICS*EXPORT)
     */
    readonly labels: {[key: string]: string};
    /**
     * The Deployments linked to the environment object
     */
    readonly links: outputs.GetEnvironmentObjectLink[];
    /**
     * The username used for the connection (only used when object_type=CONNECTION)
     */
    readonly login: string;
    /**
     * The key for the environment object
     */
    readonly objectKey: string;
    /**
     * The type of environment object (AIRFLOW*VARIABLE, CONNECTION, METRICS*EXPORT)
     */
    readonly objectType: string;
    /**
     * The password — the connection password when object*type=CONNECTION, the HTTP Basic-auth password when object*type=METRICS_EXPORT
     */
    readonly password: string;
    /**
     * The port for the connection (only used when object_type=CONNECTION)
     */
    readonly port: number;
    /**
     * The schema for the connection (only used when object_type=CONNECTION)
     */
    readonly schema: string;
    /**
     * The scope of the environment object (WORKSPACE, DEPLOYMENT)
     */
    readonly scope: string;
    /**
     * The ID of the scope entity where the environment object is created
     */
    readonly scopeEntityId: string;
    /**
     * The source scope, if resolved from a link
     */
    readonly sourceScope: string;
    /**
     * The source scope entity ID, if resolved from a link
     */
    readonly sourceScopeEntityId: string;
    /**
     * The connection type (only used when object_type=CONNECTION)
     */
    readonly type: string;
    /**
     * Environment Object last updated timestamp
     */
    readonly updatedAt: string;
    /**
     * Environment Object updater
     */
    readonly updatedBy: outputs.GetEnvironmentObjectUpdatedBy;
    /**
     * The username to connect to the remote endpoint (only used when object*type=METRICS*EXPORT)
     */
    readonly username: string;
    /**
     * The value of the Airflow variable (only used when object*type=AIRFLOW*VARIABLE)
     */
    readonly value: string;
}
/**
 * Environment Object data source
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as astronomer from "@ryan-pip/pulumi_astronomer";
 *
 * const exampleEnvironmentObject = astronomer.getEnvironmentObject({
 *     id: "cm4ntm56001gk01mbhudv1elv",
 * });
 * export const environmentObject = exampleEnvironmentObject;
 * ```
 */
export function getEnvironmentObjectOutput(args: GetEnvironmentObjectOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEnvironmentObjectResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("astronomer:index/getEnvironmentObject:getEnvironmentObject", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvironmentObject.
 */
export interface GetEnvironmentObjectOutputArgs {
    /**
     * Environment object identifier
     */
    id: pulumi.Input<string>;
}
