// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages organization, workspace, deployment, and DAG roles for an existing team. Astro permissions are hierarchical (organization, workspace, deployment, then DAG). Declare roles at each applicable parent scope as well as nested scopes, not only at the leaf, so Terraform state matches the API.
 */
export class TeamRoles extends pulumi.CustomResource {
    /**
     * Get an existing TeamRoles resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TeamRolesState, opts?: pulumi.CustomResourceOptions): TeamRoles {
        return new TeamRoles(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'astronomer:index/teamRoles:TeamRoles';

    /**
     * Returns true if the given object is an instance of TeamRoles.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TeamRoles {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TeamRoles.__pulumiType;
    }

    /**
     * The DAG roles to assign to the team. Each role grants permissions to a specific DAG or DAGs with a specific tag within a deployment. Each deployment referenced in `dagRoles` must also have a corresponding entry in `deploymentRoles` (e.g. with `DEPLOYMENT_ACCESSOR` role).
     */
    declare public readonly dagRoles: pulumi.Output<outputs.TeamRolesDagRole[] | undefined>;
    /**
     * The roles to assign to the deployments. Each `deploymentId` must belong to a workspace that also appears in `workspaceRoles`. Required for any deployment referenced in `dagRoles`.
     */
    declare public readonly deploymentRoles: pulumi.Output<outputs.TeamRolesDeploymentRole[] | undefined>;
    /**
     * The role to assign to the organization
     */
    declare public readonly organizationRole: pulumi.Output<string>;
    /**
     * The ID of the team to assign the roles to
     */
    declare public readonly teamId: pulumi.Output<string>;
    /**
     * The roles to assign to the workspaces. When you set `deploymentRoles` or `dagRoles`, include each deployment's parent workspace here (any workspace role), so Terraform state matches the API.
     */
    declare public readonly workspaceRoles: pulumi.Output<outputs.TeamRolesWorkspaceRole[] | undefined>;

    /**
     * Create a TeamRoles resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TeamRolesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TeamRolesArgs | TeamRolesState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TeamRolesState | undefined;
            resourceInputs["dagRoles"] = state?.dagRoles;
            resourceInputs["deploymentRoles"] = state?.deploymentRoles;
            resourceInputs["organizationRole"] = state?.organizationRole;
            resourceInputs["teamId"] = state?.teamId;
            resourceInputs["workspaceRoles"] = state?.workspaceRoles;
        } else {
            const args = argsOrState as TeamRolesArgs | undefined;
            if (args?.organizationRole === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationRole'");
            }
            if (args?.teamId === undefined && !opts.urn) {
                throw new Error("Missing required property 'teamId'");
            }
            resourceInputs["dagRoles"] = args?.dagRoles;
            resourceInputs["deploymentRoles"] = args?.deploymentRoles;
            resourceInputs["organizationRole"] = args?.organizationRole;
            resourceInputs["teamId"] = args?.teamId;
            resourceInputs["workspaceRoles"] = args?.workspaceRoles;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TeamRoles.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TeamRoles resources.
 */
export interface TeamRolesState {
    /**
     * The DAG roles to assign to the team. Each role grants permissions to a specific DAG or DAGs with a specific tag within a deployment. Each deployment referenced in `dagRoles` must also have a corresponding entry in `deploymentRoles` (e.g. with `DEPLOYMENT_ACCESSOR` role).
     */
    dagRoles?: pulumi.Input<pulumi.Input<inputs.TeamRolesDagRole>[] | undefined>;
    /**
     * The roles to assign to the deployments. Each `deploymentId` must belong to a workspace that also appears in `workspaceRoles`. Required for any deployment referenced in `dagRoles`.
     */
    deploymentRoles?: pulumi.Input<pulumi.Input<inputs.TeamRolesDeploymentRole>[] | undefined>;
    /**
     * The role to assign to the organization
     */
    organizationRole?: pulumi.Input<string | undefined>;
    /**
     * The ID of the team to assign the roles to
     */
    teamId?: pulumi.Input<string | undefined>;
    /**
     * The roles to assign to the workspaces. When you set `deploymentRoles` or `dagRoles`, include each deployment's parent workspace here (any workspace role), so Terraform state matches the API.
     */
    workspaceRoles?: pulumi.Input<pulumi.Input<inputs.TeamRolesWorkspaceRole>[] | undefined>;
}

/**
 * The set of arguments for constructing a TeamRoles resource.
 */
export interface TeamRolesArgs {
    /**
     * The DAG roles to assign to the team. Each role grants permissions to a specific DAG or DAGs with a specific tag within a deployment. Each deployment referenced in `dagRoles` must also have a corresponding entry in `deploymentRoles` (e.g. with `DEPLOYMENT_ACCESSOR` role).
     */
    dagRoles?: pulumi.Input<pulumi.Input<inputs.TeamRolesDagRole>[] | undefined>;
    /**
     * The roles to assign to the deployments. Each `deploymentId` must belong to a workspace that also appears in `workspaceRoles`. Required for any deployment referenced in `dagRoles`.
     */
    deploymentRoles?: pulumi.Input<pulumi.Input<inputs.TeamRolesDeploymentRole>[] | undefined>;
    /**
     * The role to assign to the organization
     */
    organizationRole: pulumi.Input<string>;
    /**
     * The ID of the team to assign the roles to
     */
    teamId: pulumi.Input<string>;
    /**
     * The roles to assign to the workspaces. When you set `deploymentRoles` or `dagRoles`, include each deployment's parent workspace here (any workspace role), so Terraform state matches the API.
     */
    workspaceRoles?: pulumi.Input<pulumi.Input<inputs.TeamRolesWorkspaceRole>[] | undefined>;
}
